### ISSUE TITLE
Support for Scoped Storage in Android

### ISSUE THREAD

**Issue by marcosPerezRubio** [hyochan/react-native-audio-recorder-player#225]
### Platforms you faced the error (IOS or Android or both?)
Android version >= 10
### Expected behavior
To use the new scoped storage solution

### Actual behavior
Recorder fails to start since no access to /sdcard is available.

### Steps to reprodue the behabior
Play the recorder in a Android >= 10 version device.

### Hints and other resources
In order to have compatibility with Android 10, a fix can be applied modifying the application tag in the manifest:

`<manifest ... >
  
  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>`

But this is only a workaround, since it will be deprecated in future versions.

Also, related implementation:
https://stackoverflow.com/questions/59327033/android-q-how-to-save-audio-recording-with-mediastore-with-the-correct-file-nam

**Comment by hyochan** [comment]
Nice issue! Could you kindly add this to our readme? It would be nice if you can give us a `PR`.

**Comment by mrigo** [comment]
@marcosPerezRubio you saved my life!
But can you record an audio? With Android >= 10 and you fix I can record an audio file but it's mute, there is no audio.
The file is heavy, is not 0 KB but it's mute.
I have also the permission to record audio so I can't get it...
@hyochan did you investigate a little in this issue?

Thanks guys!

**Comment by mrigo** [comment]
Ok found the problem...
In the simulator you have to activate the option "Microphone > Virtual microphone uses host audio input".
Never used it on other simulators, but maybe with Android >= 10 is required.

<img width="932" alt="Schermata 2020-09-24 alle 12 35 08" src="https://user-images.githubusercontent.com/2822656/94134506-64d2ad00-fe62-11ea-807f-4b721bac4f5e.png">

**Comment by Aung-Myint-Thein** [comment]
Actually, after testing on a few devices, I found the best solution that works for me and hopefully, this will help other fellow developers too.

```
import RNFetchBlob from 'rn-fetch-blob';

let dirs = RNFetchBlob.fs.dirs;
let path = Platform.select({
    ios: 'hello.m4a',
    android: `${dirs.CacheDir}/practice.mp3`,
  });
```

This path will never fails 🙂  because every app will have its own cache directory. The reason I came up with this instead of `sdcard` is that in one of the Samsung phones, it doesn't have sdcard and I think the directory is not available to set. Please try this method and hope this helps!

If this is working for @mrigo @marcosPerezRubio @hyochan , I will help to write this down in readme.

**Comment by marcosPerezRubio** [comment]
Thanks for the update, I will try it for sure.

I've in mind to document better the legacy function.

Hope we can sort it out!

**Comment by hyochan** [comment]
> Actually, after testing on a few devices, I found the best solution that works for me and hopefully, this will help other fellow developers too.
> 
> ```
> import RNFetchBlob from 'rn-fetch-blob';
> 
> let dirs = RNFetchBlob.fs.dirs;
> let path = Platform.select({
>     ios: 'hello.m4a',
>     android: `${dirs.CacheDir}/hello.mp3`,
>   });
> ```
> 
> This path will never fails 🙂 because every app will have its own cache directory. The reason I came up with this instead of `sdcard` is that in one of the Samsung phones, it doesn't have sdcard and I think the directory is not available to set. Please try this method and hope this helps!
> 
> If this is working for @mrigo @marcosPerezRubio @hyochan , I will help to write this down in readme.

I've recommend this approach from `2.7.0` and updated the readme. Thanks 🙌

**Comment by Steve-Rynjah** [comment]
import RNFetchBlob from 'rn-fetch-blob';

let dirs = RNFetchBlob.fs.dirs;
let path = Platform.select({
    ios: 'hello.m4a',
    android: `${dirs.CacheDir}/hello.mp3`,
  });

I don't see the file in my device @Aung-Myint-Thein, and for such I guess I'm facing an error on playing the audio saying : open failed: ENOENT (No such file or directory)
