### ISSUE TITLE
Stop Recording is not working in functional components

### ISSUE THREAD

**Issue by RTBYab** [hyochan/react-native-audio-recorder-player#238]
### Version of react-native-audio-recorder-player
  "react-native-audio-recorder-player": "^2.6.0-rc3",
### Platforms you faced the error (IOS or Android or both?)
IOS

onStopRecord = async () => {
    const result = await audioRecorderPlayer.stopRecorder();
    audioRecorderPlayer.removeRecordBackListener();
      setRecordSecs(0);
    console.log(result);
  };

### Expected behavior
Stop recording 
### Actual behavior
when I change the class based comp to functional 
onStopRecord is not working any more and shows already stops in console

**Comment by sow1ch** [comment]
> ### Version of react-native-audio-recorder-player
> "react-native-audio-recorder-player": "^2.6.0-rc3",
> 
> ### Platforms you faced the error (IOS or Android or both?)
> IOS
> 
> onStopRecord = async () => {
> const result = await audioRecorderPlayer.stopRecorder();
> audioRecorderPlayer.removeRecordBackListener();
> setRecordSecs(0);
> console.log(result);
> };
> 
> ### Expected behavior
> Stop recording
> 
> ### Actual behavior
> when I change the class based comp to functional
> onStopRecord is not working any more and shows already stops in console
> 
> ### Steps to reprodue the behabior

Move 
```
const audioRecorderPlayer = new AudioRecorderPlayer();
```
in useEffect or move it outside the component
