### ISSUE TITLE
How to save the files not in the default position?

### ISSUE THREAD

**Issue by wingchan1224** [hyochan/react-native-audio-recorder-player#240]
### Version of react-native-audio-recorder-player
Newest
### Platforms you faced the error (IOS or Android or both?)
iOS and Android
### Expected behavior
Save the file in AWS S3 bucket or local first with the following code:
``` const path = Platform.select({
      ios: "/Users/username/projectname/src/audio/hello.m4a",
      android:  "/Users/username/projectname/src/audio/hello.m4a",
    });
```
### Actual behavior
save the file in 
file:///Users/username/Library/Developer/CoreSimulator/Devices/BCFEFCD8-C81D-4CB9-8B91-507D4C57D564/data/Containers/Data/Application/3339B5B3-6641-48BD-A2E3-7A73DF5B1F82/Library/Caches//Users/username/tprojectname/src/audio/hello.m4a

**Comment by alexisedm** [comment]
Can you solved this problem?

**Comment by NewTech2000** [comment]
Possible Unhandled Promise Rejection (id: 0):
Error: /Users/username/permia_Sensing/src/audio/hello.m4a: open failed: ENOENT (No such file or directory)

**Comment by wingchan1224** [comment]
> Can you solved this problem?

seems solved finally

**Comment by Aung-Myint-Thein** [comment]
I faced this issue just now. When we are using FileSystem from Expo, the player cannot record. So I checked the file paths and found out that rnfetchblob's cacheDir will start with `/` but Expo's Filesystem starts with `file://` and it is the main reason breaking. So, when I removed the `file://` from expo's filesystem, it is working now :D
