### ISSUE TITLE
Record another audio file not working

### ISSUE THREAD

**Issue by wingchan1224** [hyochan/react-native-audio-recorder-player#243]
### Version of react-native-audio-recorder-player
"react-native-audio-recorder-player": "^2.6.0-rc3",
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
record another audio in another path
### Actual behavior
show the uri: Already recording
### Steps to reprodue the behabior

When I start record and play at the very beginning, it works fine, I can get the manual path and play it, but when I try to record another file, the uri is Already recording, that means I can't generate another audio record.

**Comment by joaojeefer** [comment]
Do you generate your path dynamically?
If you generate your path, maybe using a uuid lib to help you, every time you are up to recorder this will work fine.

**Comment by hyochan** [comment]
Try use [rn-fetch-blob]() as told in the [README#tips](https://github.com/hyochan/react-native-audio-recorder-player#tips)
