### ISSUE TITLE
Not able to play audio files through the URL 

### ISSUE THREAD

**Issue by ahmad6242** [hyochan/react-native-audio-recorder-player#245]
### Version of react-native-audio-recorder-player
2.6.0

### Platforms you faced the error (IOS or Android or both?)
Android currently. but will test on IOS also later

### Expected behavior
https://ieducore.org/portal/attachments/images/center/2/stdassign/assign_5fcf71979de20.mp4
var path = Platform.select({
            ios: url,
            android: url,
        });
var msg = await this.audioRecorderPlayer.startPlayer(path);
console.log('msg', msg);

it is taking so much time to reach to the console. and not able to play it 
Showing warning on react native app
prepare failed: status0*1

### Actual behavior
It should play the audio immediately after calling it. 

### Steps to reprodue the behabior
Just try to run any audio through URL.

**Comment by hyochan** [comment]
Please try `3.0.0-beta.1` if you have time.

Closes via #284

**Comment by praveshkumarpal** [comment]
> Yeah, it works on iOS but not on Android.

Yes i am facing same issue how can solve this, i am record the audio .m4a extension file and in IOS play this audio but in android not play .m4a file extension.
