### ISSUE TITLE
Getting Warning audioPlayer is not set

### ISSUE THREAD

**Issue by divyagoel-kiwi** [hyochan/react-native-audio-recorder-player#252]
Hi-

I am new in react native and used this library for my project. It works perfectly however I am getting warning audioPlayer is not set most of the time. Can any one of you please tell me what is thee possible cause of this warning

**Comment by patrickbattisti** [comment]
you need ensure that has firing the startPlayer before all other methods.

eg:

 **don't working**
audioRecorderPlayer.seekToPlayer();
audioRecorderPlayer.startPlayer();


**working**
audioRecorderPlayer.startPlayer();
audioRecorderPlayer.seekToPlayer();
