### ISSUE TITLE
What is the absolute URI of the recorded audio?

### ISSUE THREAD

**Issue by DevanshuQuovantis** [hyochan/react-native-audio-recorder-player#253]
If I want to play the recorded audio in other media player, for example: react-native-video, what should the full URI that needs to be passed to the source prop at media player.
I can see that, in documentation - only the file name is mentioned.

**Comment by DevanshuQuovantis** [comment]
Close to 3 hours toiling, for playing the recorder audio via react-native-video, for both platforms Android & iOS,
I finally managed to get the absolute URI where our recorded audio is stored.
To pass absolute URI in source prop for any other media player(I am using react-native-video)
**For Android:** 
`'file:///' + 'sdcard/hello.mp4'`.
**For iOS:** 
We first need to get CachesDirectoryPath. To fetch this path, use RNFS, then add - 
`RNFS.CachesDirectoryPath + '/' + 'hello.m4a'`;

**Comment by progsmile** [comment]
Hey @DevanshuQuovantis !
Please, help to figure out: what path I should provide to play mp3 files in project dir `./assets` ?

**Comment by hyochan** [comment]
Try use [rn-fetch-blob](https://www.npmjs.com/package/rn-fetch-blob) as told in the [README#tips](https://github.com/hyochan/react-native-audio-recorder-player#tips) for the file access.
