### ISSUE TITLE
startRecorder crashes app + warning about no rn-recordback registered

### ISSUE THREAD

**Issue by raeez** [hyochan/react-native-audio-recorder-player#256]
### Version of react-native-audio-recorder-player
2.6.1

### Platforms you faced the error (IOS or Android or both?)
IOS 14.3 and 14.4

### Expected behavior
Code from Example runs

### Actual behavior
`startRecorder() `crashes the component, and fires a warning `"sending rn-recordback with no listeners registered"`— anyway, the callBack I register still fires, e.g. we see the log output of            `console.log('audio/OnStartRecord::recordBackListener', e);`
 in
`const result = await this.context.audioManager.startRecorder();
       this.context.audioManager.addRecordBackListener((e) => {
         const currentSecs = Math.floor(e.current_position);
         const mmssss = this.context.audioManager.mmssss(
           Math.floor(e.current_position),
         );
           this.setAudioRecorderRecordSecs(currentSecs);
           this.setAudioRecorderRecordTime(mmssss);
           console.log('audio/OnStartRecord::recordBackListener', e);
       });
        console.log('audio/result', result); `
### Steps to reprodue the behabior
adapt the example code as above. Example code also builds, but launches to a white screen on iOS simulators 14.3 and 14.4.

**Comment by DawidNRay** [comment]
I have the same problem. Did you found the solution?

**Comment by raeez** [comment]
no progress; instead switched to `react-native-audio-toolkit`

**Comment by efstathiosntonas** [comment]
This is a known bug on the iOS simulator, on real devices it should be fine.

**Comment by Wanderlust-sol** [comment]
but I had same problem on real devices...

**Comment by DawidNRay** [comment]
What worked for me was adding to Info.plist file
`<key>NSMicrophoneUsageDescription</key>
<string>${PRODUCT_NAME} wants to have access to microphone</string>`

After that cd into ios folder and run `pod install && pod update`

**Comment by anniewey** [comment]
@Aakash007-ai can try set your own listener. had the same issue in ios and added the listener to fix it

```
const audioRecorderPlayer = useRef(new AudioRecorderPlayer()).current;
const recordBackListenerRef = useRef<any>(null);

  useEffect(() => {
    recordBackListenerRef.current = audioRecorderPlayer.addRecordBackListener(
      () => {},
    );

    return () => {
      audioRecorderPlayer.removeRecordBackListener();
    };
  }, [audioRecorderPlayer]);
```
