### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNAudioRecorderPlayer.startRecorder')

### ISSUE THREAD

**Issue by nickdekesel** [hyochan/react-native-audio-recorder-player#258]
### Version of react-native-audio-recorder-player
2.6.1

### Platforms you faced the error (IOS or Android or both?)
Android and Web

### Expected behavior
Audio recorder is not null and startRecorder can be called

### Actual behavior
Audio recorder is null

### Steps to reproduce the behavior
Use the example in combination with expo sdk version 40.0.1

**Comment by ronaldocala** [comment]
I get the same error, the IOS is working fine, but the android is giving "TypeError: null is not an object (evaluating 'RNAudioRecorderPlayer.startRecorder')", is there any solution to this yet ?

**Comment by hyochan** [comment]
Looks like you are using it in expo managed workflow. This is not supported in managed workflow since this is a native module.
