### ISSUE TITLE
Not recording audio on phones having no external SD card

### ISSUE THREAD

**Issue by imAunAbbas** [hyochan/react-native-audio-recorder-player#259]
### Version of react-native-audio-recorder-player:
2.6.1

### Platforms:
Android

### Expected behavior:
It should also allow devices that use internal storage, not SD cards by default.

### Actual behavior:
Currently, it is working fine on the devices that have SD cards, but it is not working on the devices that use internal storage. I also tried to give the internal storage path but it is not picking it up. Maybe I'm using the wrong path for internal storage but there is no path given in the documentation.

Kindly give me any solution to this problem. Thanks

**Comment by hapo-vupq** [comment]
same problem...

**Comment by imAunAbbas** [comment]
@hapo-vupq Alternative solution to this problem is to install the `rn-fetch-blob` library and use the cache directory of the application.

Example:

```
import RNFetchBlob from 'rn-fetch-blob';
const dirs = RNFetchBlob.fs.dirs;
const path = `${dirs.CacheDir}/hello.mp3`;
```

Use this path in the functions. Remember, all other directory paths are not usable except the `CacheDar`.

Usage of the path:

```
const result = await audioRecorderPlayer.startRecorder(path);
const msg = await audioRecorderPlayer.startPlayer(path);
```

**Comment by hapo-vupq** [comment]
@imAunAbbas oh, thank you. it was solved

**Comment by hyochan** [comment]
Readme provided in  [TIPS](https://github.com/hyochan/react-native-audio-recorder-player#tips).
