### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'startRecorder' of undefined using expo when starting to record

### ISSUE THREAD

**Issue by bennoheld** [hyochan/react-native-audio-recorder-player#260]
I want to implement a simple app recording audio using expo since I´m a beginner in mobile development.
After getting the necessary permisions and pressing the Start Recording button, the app crashes with the error shown in the title.

**Here is the running code on [snack.exo.io](https://snack.expo.io/W2HJ6lMQ3)**

### Version of react-native-audio-recorder-player
package.json
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-audio-recorder-player": "^2.6.1",
    "react-native-permissions": "^3.0.1",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-dom": "~16.9.8",
    "@types/react-native": "~0.63.2",
    "typescript": "~4.0.0"
  },
  "private": true
}
```

### Platforms you faced the error (IOS or Android or both?)
Android & Web
![android_info](https://user-images.githubusercontent.com/45826043/109555226-90bf2200-7ad5-11eb-8d54-5f7dfcc63901.PNG)

### Expected behavior
I run an react native app using expo.
I am using an android emulator running Android 11
After giving the application the permissions to write to external storage and to access the microphone, I press the _Start Recording_ Button. The Recording should start and a String should be printed to the console.

### Actual behavior
When pressing _Start Recording_ an error occurs in the browser console:

> Uncaught (in promise) TypeError: Cannot read property 'startRecorder' of undefined
    at _callee$ (index.ts:182)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:189
    at new Promise (<anonymous>)
    at callInvokeWithMethodAndArg (runtime.js:188)
    at AsyncIterator.enqueue [as _invoke] (runtime.js:211)
    at AsyncIterator.next (runtime.js:118)
    at Object.[PATH]\node_modules\regenerator-runtime\runtime.js.exports.async (runtime.js:238)
    at AudioRecorderPlayer._callee [as startRecorder] (index.ts:182)
    at onStartRecord$ (App.tsx:87)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:189
    at new Promise (<anonymous>)
    at callInvokeWithMethodAndArg (runtime.js:188)
    at AsyncIterator.enqueue [as _invoke] (runtime.js:211)
    at AsyncIterator.next (runtime.js:118)
    at Object.[PATH]\node_modules\regenerator-runtime\runtime.js.exports.async (runtime.js:238)
    at onStartRecord (App.tsx:73)
    at onPress (App.tsx:127)
    at onClick (PressResponder.js:333)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306)
    at executeDispatch (react-dom.development.js:389)
    at executeDispatchesInOrder (react-dom.development.js:411)
    at executeDispatchesAndRelease (react-dom.development.js:3278)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:3287)
    at forEachAccumulated (react-dom.development.js:3259)
    at runEventsInBatch (react-dom.development.js:3304)
    at runExtractedPluginEventsInBatch (react-dom.development.js:3514)
    at handleTopLevel (react-dom.development.js:3558)
    at batchedEventUpdates$1 (react-dom.development.js:21871)
    at batchedEventUpdates (react-dom.development.js:795)
    at dispatchEventForLegacyPluginEventSystem (react-dom.development.js:3568)
    at attemptToDispatchEvent (react-dom.development.js:4267)
    at dispatchEvent (react-dom.development.js:4189)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at discreteUpdates$1 (react-dom.development.js:21887)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)

This Appears in the Android emulator

> [Unhandled promise rejection: TypeError: null is not an object (evaluating 'RNAudioRecorderPlayer.startRecorder')]
> Stack trace:
> node_modules\react-native-audio-recorder-player\index.ts:188:6 in AudioRecorderPlayer#startRecorder
>   node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
>   node_modules\regenerator-runtime\runtime.js:293:29 in invoke
>   node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
>   node_modules\regenerator-runtime\runtime.js:154:27 in invoke
>   node_modules\regenerator-runtime\runtime.js:189:16 in PromiseImpl$argument_0
>   node_modules\react-native\node_modules\promise\setimmediate\core.js:45:6 in tryCallTwo
>   node_modules\react-native\node_modules\promise\setimmediate\core.js:200:22 in doResolve
>   node_modules\react-native\node_modules\promise\setimmediate\core.js:66:11 in Promise
>   node_modules\regenerator-runtime\runtime.js:188:15 in callInvokeWithMethodAndArg
>   node_modules\regenerator-runtime\runtime.js:211:38 in enqueue
>   node_modules\regenerator-runtime\runtime.js:238:8 in exports.async
>   node_modules\react-native-audio-recorder-player\index.ts:182:18 in AudioRecorderPlayer#startRecorder
>   App.tsx:85:8 in onStartRecord
>   node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
>   node_modules\regenerator-runtime\runtime.js:293:29 in invoke
>   node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
>   node_modules\regenerator-runtime\runtime.js:154:27 in invoke
>   node_modules\regenerator-runtime\runtime.js:189:16 in PromiseImpl$argument_0
>   node_modules\react-native\node_modules\promise\setimmediate\core.js:45:6 in tryCallTwo
>   node_modules\react-native\node_modules\promise\setimmediate\core.js:200:22 in doResolve
>   node_modules\react-native\node_modules\promise\setimmediate\core.js:66:11 in Promise
>   node_modules\regenerator-runtime\runtime.js:188:15 in callInvokeWithMethodAndArg
>   node_modules\regenerator-runtime\runtime.js:211:38 in enqueue
>   node_modules\regenerator-runtime\runtime.js:238:8 in exports.async
>   App.tsx:73:26 in onStartRecord
>   App.tsx:127:58 in Button.props.onPress
>   node_modules\react-native\Libraries\Pressability\Pressability.js:691:17 in _performTransitionSideEffects
>   node_modules\react-native\Libraries\Pressability\Pressability.js:628:6 in _receiveSignal
>   node_modules\react-native\Libraries\Pressability\Pressability.js:524:8 in responderEventHandlers.onResponderRelease
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:265:4 in invokeGuardedCallbackImpl
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:476:2 in invokeGuardedCallback
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:500:2 in invokeGuardedCallbackAndCatchFirstError
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:597:41 in executeDispatch
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:621:19 in executeDispatchesInOrder
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2521:28 in executeDispatchesAndRelease
>   [native code]:null in forEach
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:836:4 in forEachAccumulated
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2546:20 in runEventsInBatch
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2702:18 in runExtractedPluginEventsInBatch
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2639:35 in batchedUpdates$argument_0
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17712:13 in batchedUpdates$1
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2492:29 in batchedUpdates
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2638:16 in _receiveRootNodeIDEvent
>   node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2767:27 in receiveTouches
>   node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
>   node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
>   node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
>   node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
>   [native code]:null in callFunctionReturnFlushedQueue
>   ...

Expo output in the browser:
![error_web](https://user-images.githubusercontent.com/45826043/109556714-75551680-7ad7-11eb-9cfb-8934dac90f01.PNG)

The `console.log(audioRecorderPlayer)` is printing 

> AudioRecorderPlayer {mmss: ƒ, mmssss: ƒ, addRecordBackListener: ƒ, removeRecordBackListener: ƒ, addPlayBackListener: ƒ, …}
> addPlayBackListener: ƒ (e)
> addRecordBackListener: ƒ (e)
> mmss: ƒ (secs)
> mmssss: ƒ (milisecs)
> pausePlayer: ƒ _callee6()
> removePlayBackListener: ƒ ()
> removeRecordBackListener: ƒ ()
> resumePlayer: ƒ _callee3()
> seekToPlayer: ƒ _callee7(time)
> setSubscriptionDuration: ƒ _callee9(sec)
> setVolume: ƒ _callee8(volume)
> startPlayer: ƒ _callee4(uri, httpHeaders)
> startRecorder: ƒ _callee(uri, audioSets, meteringEnabled)
> stopPlayer: ƒ _callee5()
> stopRecorder: ƒ _callee2()
> _isRecording: true
> __proto__: Object

### Steps to reproduce the behavior

**Here is the running code on [snack.exo.io](https://snack.expo.io/W2HJ6lMQ3)**

**Comment by danieloi** [comment]
This library isn't supported in a managed workflow with expo. 
You need to eject or use the expo-av library instead.

**Comment by fukemy** [comment]
im using cli but still got this error.any solution here?
