### ISSUE TITLE
Can you change the format of audio?

### ISSUE THREAD

**Issue by DawidNRay** [hyochan/react-native-audio-recorder-player#262]
As I've seen, the default format is m4a for ios and mp4 for android, but can you change it to f.e. acc?

**Comment by Yandamuri** [comment]
if you mean while recording, Then .acc is already working. I am using the same format

**Comment by vitorverasm** [comment]
.acc format is working for me on android.

my audio settings:
```js
const audioSet = {
    AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
    AudioSourceAndroid: AudioSourceAndroidType.MIC,
    AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high,
    AVNumberOfChannelsKeyIOS: 2,
    AVFormatIDKeyIOS: AVEncodingOption.aac
};
```

**Comment by SanjaySargam** [comment]
I want to change the audio format to .mp3 
How can I achieve it ?

**Comment by Yandamuri** [comment]
> I want to change the audio format to .mp3
> How can I achieve it ?

Have you tried `OutputFormatAndroid`?

https://github.com/hyochan/react-native-audio-recorder-player#able-to-customize-recorded-audio-quality-from-230

**Comment by SanjaySargam** [comment]
```
export declare enum AudioSourceAndroidType {
    DEFAULT = 0,
    MIC = 1,
    VOICE_UPLINK = 2,
    VOICE_DOWNLINK = 3,
    VOICE_CALL = 4,
    CAMCORDER = 5,
    VOICE_RECOGNITION = 6,
    VOICE_COMMUNICATION = 7,
    REMOTE_SUBMIX = 8,
    UNPROCESSED = 9,
    RADIO_TUNER = 1998,
    HOTWORD = 1999
}
```


but it does not have mp3 format

**Comment by Yandamuri** [comment]
> ```
> export declare enum AudioSourceAndroidType {
>     DEFAULT = 0,
>     MIC = 1,
>     VOICE_UPLINK = 2,
>     VOICE_DOWNLINK = 3,
>     VOICE_CALL = 4,
>     CAMCORDER = 5,
>     VOICE_RECOGNITION = 6,
>     VOICE_COMMUNICATION = 7,
>     REMOTE_SUBMIX = 8,
>     UNPROCESSED = 9,
>     RADIO_TUNER = 1998,
>     HOTWORD = 1999
> }
> ```
> 
> 
>     
>   
> 
> but it does not have mp3 format

            let file name = 'AudioFile';
            let audioPath = <path> + fileName.replace(/[^a-zA-Z0-9]/g, '_') + '.mp3';
            const result = await this.audioRecorderPlayer.startRecorder(audioPath);

**Comment by SanjaySargam** [comment]
> > ```
> > export declare enum AudioSourceAndroidType {
> >     DEFAULT = 0,
> >     MIC = 1,
> >     VOICE_UPLINK = 2,
> >     VOICE_DOWNLINK = 3,
> >     VOICE_CALL = 4,
> >     CAMCORDER = 5,
> >     VOICE_RECOGNITION = 6,
> >     VOICE_COMMUNICATION = 7,
> >     REMOTE_SUBMIX = 8,
> >     UNPROCESSED = 9,
> >     RADIO_TUNER = 1998,
> >     HOTWORD = 1999
> > }
> > ```
> > 
> > 
> >     
> >   
> > 
> > but it does not have mp3 format
> 
>             let file name = 'AudioFile';
>             let audioPath = <path> + fileName.replace(/[^a-zA-Z0-9]/g, '_') + '.mp3';
>             const result = await this.audioRecorderPlayer.startRecorder(audioPath);

Ok I will try this 
And Let you know

**Comment by Kumar6174** [comment]
> > ```
> > export declare enum AudioSourceAndroidType {
> >     DEFAULT = 0,
> >     MIC = 1,
> >     VOICE_UPLINK = 2,
> >     VOICE_DOWNLINK = 3,
> >     VOICE_CALL = 4,
> >     CAMCORDER = 5,
> >     VOICE_RECOGNITION = 6,
> >     VOICE_COMMUNICATION = 7,
> >     REMOTE_SUBMIX = 8,
> >     UNPROCESSED = 9,
> >     RADIO_TUNER = 1998,
> >     HOTWORD = 1999
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but it does not have mp3 format
> 
> ```
>         let file name = 'AudioFile';
>         let audioPath = <path> + fileName.replace(/[^a-zA-Z0-9]/g, '_') + '.mp3';
>         const result = await this.audioRecorderPlayer.startRecorder(audioPath);
> ```

This method does not works if we want to play recording in native music player
