### ISSUE TITLE
recordSecs jumps from 0 to 640357309.478458 ??

### ISSUE THREAD

**Issue by pjadavies** [hyochan/react-native-audio-recorder-player#263]
Marking this as a question because I assume I've done something stupid but I can't figure out what :) Hopefully someone else has seen similar and can point me in the right direction!

### Version of react-native-audio-recorder-player
2.6.0

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
recordSecs increments sequentially, one second at a time

### Actual behavior
I'm using the example files (largely copy/pasted into a new React Native app, with some additions, but no modifications to the actual play functionality)

When I start recording, the counters are all over the place. When I `console.log(e)` I see:
```
{"current_metering": "0", "current_position": "640510837.0748299"}
```

**Comment by hyochan** [comment]
Looks like there is some logical problem in handling the audio recorder and player. We need more investigation to handle your problem.

**Comment by Muhammadtayyabb** [comment]
The issue is also present on android but it does not occurs every time it occurs mostly when we start stop recorder multiple times quickly.

**Comment by KrisLau** [comment]
@hyochan I'm having the same issue as @Muhammadtayyabb
