### ISSUE TITLE
Is it possible to play the cloud file

### ISSUE THREAD

**Issue by Yandamuri** [hyochan/react-native-audio-recorder-player#265]
### "react-native-audio-recorder-player": "^2.6.1"

As of now only downloaded files are able to play. I have not seen documents mentioned about playing cloud files. Is this possible?

**Comment by progsmile** [comment]
Hey @Yandamuri !
Is it able to play even local files? I can't get what path should I provide if I have mp3 files in project dir `./assets`

**Comment by Yandamuri** [comment]
@progsmile try like this

      const path = Platform.select({
	        ios: 'file://' + localPath,
		android: localPath
       })
       const msg = await this.audioRecorderPlayer.startPlayer(path);

**Comment by hyochan** [comment]
Try use [rn-fetch-blob](https://www.npmjs.com/package/rn-fetch-blob) as told in the [README#tips](https://github.com/hyochan/react-native-audio-recorder-player#tips) for the file access.
