### ISSUE TITLE
Audio is still playing even after closing the app

### ISSUE THREAD

**Issue by Yandamuri** [hyochan/react-native-audio-recorder-player#267]
### Steps to reprodue the behabior

1. Play any audio.
2. Then close the app, You can notice that still audio is playing
3. Try to kill the app. You can notice still audio is playing

Note: When audio is playing app is not getting killed when tried by app switcher

**Comment by usmansbk** [comment]
Call stopPlayer in useEffect return callback or componentWillIUnmount

**Comment by Yandamuri** [comment]
@usmansbk In fact,  componentWillIUnmount is not being called when I close the app. Any alter native to stop audio when app is closed?

**Comment by efstathiosntonas** [comment]
use `AppState`

```

import {AppState} from 'react-native';

useEffect(() => {
    const listener = (status: AppStateStatus) => {
      if (status === "background" || status === "inactive") {
        stopPlayer().catch((e) =>
          console.log(`error while stopping player on unmount, ${e}`)
        );
      }
    };
    AppState.addEventListener("change", listener);
    return () => {
      AppState.removeEventListener("change", listener);
    };
  }, []);
```

**Comment by Yandamuri** [comment]
@efstathiosntonas Great 👍 Your solution is working. May I know when exactly below statements are executed,

     AppState.addEventListener("change", listener);
    return () => {
      AppState.removeEventListener("change", listener);
    };

**Comment by vitorverasm** [comment]
@Yandamuri you could refer to [this documentation](https://reactnative.dev/docs/appstate)

**Comment by hyochan** [comment]
Looks like the issue is resolved!
