### ISSUE TITLE
 [Error: Error not specified.] promise rejection when starting recorder in android 9

### ISSUE THREAD

**Issue by JorSargsyan** [hyochan/react-native-audio-recorder-player#272]
### Version of react-native-audio-recorder-player
^2.6.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
It works normally in android 10.

### Actual behavior
when starting on android 9 device,java throws illegalStateException,which means that I tried to start mediaRecorder without calling prepare() fn.

**Comment by ph98** [comment]
same problem

**Comment by hyochan** [comment]
Could you try `2.7.0` and come back?

**Comment by sootood** [comment]
same problem on 2.7.0

**Comment by hyochan** [comment]
How about `3.0.0-beta.2`?

**Comment by hyochan** [comment]
@sootood Also please try the `example` project either and see the differences.

**Comment by hyochan** [comment]
Looks like this is a default `path` problem that is resolved in `3.0.+`.

**Comment by PepeValenzuela98** [comment]
> Looks like this is a default `path` problem that is resolved in `3.0.+`.

I'm using the 3.0.2 version and i'm still with the same problem in Android 7 and 9 in Android 10 works fine
