### ISSUE TITLE
[Feature request] Stream in chunks

### ISSUE THREAD

**Issue by sayem314** [hyochan/react-native-audio-recorder-player#275]
### Version of react-native-audio-recorder-player

2.6.2

### Platforms you faced the error (IOS or Android or both?)

both

###  Behavior

When playing a large podcast file from remote location it's not streaming in chunks/real-time but instead, it's downloading it fully first. The server is sending proper responses. `react-native-video` package plays as expected so it's not server-side issue.

**Comment by hyochan** [comment]
This is a limitation on [AVAudioPlayer](https://developer.apple.com/documentation/avfaudio/avaudioplayer) which we are using. Currently, I am looking to migrate to [AVPlayer](https://developer.apple.com/documentation/avfoundation/avplayer) as described in #284

**Comment by hyochan** [comment]
Please try `3.0.0-beta.1` if you have time.

Closes via #284

**Comment by milesscherrer** [comment]
Not sure if streaming works in 3.1.0, or at least playback has a long delay on remote files. Starting playback of remote files takes > 3 seconds even on fast network.

Tried to add:

audioPlayer.automaticallyWaitsToMinimizeStalling = false
audioPlayerItem.preferredForwardBufferDuration = 1.0
audioPlayer.playImmediately(atRate: 1.0)

but playback still takes > 3 seconds to start and these settings seems to have no effect.

As it audio file size does not seem change start delay, maybe streaming is working. But then it is still a problem that there is a major delay on start play.

**Comment by tragicmj** [comment]
Facing the same problem, any solution found?? @milesscherrer 
This issue should be open @hyochan

**Comment by devlprkhan** [comment]
Same is there any way to stream audio recording and send the live audio recording chunks using data stream methods to our server, my main issue is that there is any way? to get realtime audio chunks while recording :(,

**Comment by innvonix-tasktalk** [comment]
@devlprkhan have you find any solution to stream audio recording and send the live audio recording chunks to server ?
I am in urgent need of help in that regard.

**Comment by H3tansh** [comment]
@devlprkhan have you find any solution to record audio stream and send audio chunks to server ?, I am in urgent need of help regarding that

**Comment by saintpepsicola** [comment]
@milesscherrer @devlprkhan  Did you guys find any solution? Thanks

**Comment by H3tansh** [comment]
@devlprkhan Can you please share your working code snippet if possible, 
Thanks a lot!!!

**Comment by Iamfavur** [comment]
@devlprkhan i installed the package on my reactnative version 0.76.1, which is the new architecture and my android app is not building, seeing error of:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-live-audio-stream:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-live-audio-stream:debugCompileClasspath'.
Warning: Failed to parse host 192.53.67.218:5767
```
...
...
....
other error messages

but it builds successfully on IOS.
