### ISSUE TITLE
How to convert  record data while recording in PCM format

### ISSUE THREAD

**Issue by gopikasireddy202** [hyochan/react-native-audio-recorder-player#280]
const onStartRecord =  async()=> {

    var arr = [];
    const path = Platform.select({
      ios: 'hello.m4a',
      android: 'sdcard/hello' + new Date().getMilliseconds() + '.mp4', // should give extra dir name in android. Won't grant permission to the first level of dir.
    });
    const audioSet  = {
            AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
            AudioSourceAndroid: AudioSourceAndroidType.MIC,
            AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high,
            AVNumberOfChannelsKeyIOS: 1,
            AVFormatIDKeyIOS: AVEncodingOption.aac,
            
        };
        const meteringEnabled = true;
       const result = await audioRecorderPlayer.startRecorder(path,audioSet,meteringEnabled);
      audioRecorderPlayer.addRecordBackListener((e) => {
        setrecordSecs(e.current_position),
        setrecordTime(audioRecorderPlayer.mmssss(Math.floor(e.current_position)));
        let decibels = Math.floor(e.current_metering);
        // console.log("Decibals"+decibels)
        arr.push(decibels);
        const obj = arr.map((val) => {
          return {...val, "y": Math.abs(val)};
      });
      setchartData(obj);
      return;
    });
  
  };

**Comment by hyochan** [comment]
Try use [rn-fetch-blob](https://www.npmjs.com/package/rn-fetch-blob) as told in the [README#tips](https://github.com/hyochan/react-native-audio-recorder-player#tips) for the file access.
