### ISSUE TITLE
pod install error RNAudioRecorderPlayer (from `../node_modules/react-native-audio-recorder-player`)

### ISSUE THREAD

**Issue by hufans** [hyochan/react-native-audio-recorder-player#290]
> Please use the 

### when Run Pod install I got this 'CocoaPods could not find compatible versions for pod "RNAudioRecorderPlayer":
  In Podfile:
    RNAudioRecorderPlayer (from `../node_modules/react-native-audio-recorder-player`)

**Comment by gopikasireddy202** [comment]
I got same error while using below steps

1) npm install react-native-audio-recorder-player --save
2) cd ios
3) pod install
[!] CocoaPods could not find compatible versions for pod "RNAudioRecorderPlayer":
  In Podfile:
    RNAudioRecorderPlayer (from `../node_modules/react-native-audio-recorder-player`)

Specs satisfying the `RNAudioRecorderPlayer (from `../node_modules/react-native-audio-recorder-player`)` dependency were found, but they required a higher minimum deployment target.
