### ISSUE TITLE
iOS Sending `rn-recordback` with no listeners registered. stop record not working

### ISSUE THREAD

**Issue by hufans** [hyochan/react-native-audio-recorder-player#291]
> Please use the 

### [Mon May 10 2021 16:38:00.330]  LOG      file:///var/mobile/Containers/Data/Application/401C1F9B-8F21-4A52-9D45-BA3E2D/Library/Caches/sound.m4a ===================start 
[Mon May 10 2021 16:38:00.912]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:01.332]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:01.838]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:02.260]  GROUPCOLLAPSED  ..  %c action %cLocationActions/locationLive %c@ 16:38:01.987 color: gray; font-weight: lighter; color: inherit; color: gray; font-weight: lighter;  (viewable in debugger)
[Mon May 10 2021 16:38:02.335]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:02.863]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:03.375]  GROUPCOLLAPSED  ..  %c action %cLocationActions/locationLive %c@ 16:38:03.654 color: gray; font-weight: lighter; color: inherit; color: gray; font-weight: lighter;  (viewable in debugger)
[Mon May 10 2021 16:38:03.830]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:04.418]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:04.846]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:05.353]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:05.837]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:06.338]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:06.878]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:06.959]  GROUPCOLLAPSED  ..  %c action %cSystemActionTypes/OnNetworkStateChange %c@ 16:38:06.905 color: gray; font-weight: lighter; color: inherit; color: gray; font-weight: lighter;  (viewable in debugger)
[Mon May 10 2021 16:38:07.339]  WARN     Sending `rn-recordback` with no listeners registered.
[Mon May 10 2021 16:38:07.421]  WARN     Possible Unhandled Promise Rejection (id: 0):
Error: Faled to stop recorder
promiseMethodWrapper@http://192.168.50.225:8081/index.bundle?platform=ios&dev=true&minify=false:2277:45

**Comment by hufans** [comment]
@hyochan 
rn-recordback with no listeners registered. Has been resolved, stop recrod still error 

isteners registered issue from 
/**
     * Set listerner from native module for recorder.
     * @returns {callBack((e: RecordBackType): void)}
     */
    addRecordBackListener: (e: RecordBackType) => void;

according this comments code should be 

current.addRecordBackListener = (e: RecordBackType) => {
    console.log(e.currentMetering);
  };

so I got this error;


this line should be 

  addRecordBackListener(e: (e: RecordBackType) => void): void

**Comment by hufans** [comment]
I got error with this line 
<img width="1578" alt="WeChat1d3b955e1ae39154eca06e81d41b642f" src="https://user-images.githubusercontent.com/20341671/117644787-7338c380-b1bc-11eb-9408-168e16583c80.png">

**Comment by hyochan** [comment]
> I got error with this line
> <img alt="WeChat1d3b955e1ae39154eca06e81d41b642f" width="1578" src="https://user-images.githubusercontent.com/20341671/117644787-7338c380-b1bc-11eb-9408-168e16583c80.png">

Please open up another issue if you want to start the new thread.

Also try to use `try` and `catch` statement in this case.

**Comment by milesscherrer** [comment]
Also have this issue in release mode, sorry not following the conversation here is there a solution?

**Comment by yzaguirre** [comment]
After the `startRecorder` call, add an empty record listener. Like this:

```javascript
this.audioRecorderPlayer.addRecordBackListener((e) => {})
```
En when `stopRecorder` is called, do remove the listener:

```javascript
this.audioRecorderPlayer.removeRecordBackListener()
```

Worked for me. I don't use that listener while recording, but iOS needs it.

**Comment by NoahSimajji** [comment]
> After the `startRecorder` call, add an empty record listener. Like this:
> 
> ```js
> this.audioRecorderPlayer.addRecordBackListener((e) => {})
> ```
> 
> En when `stopRecorder` is called, do remove the listener:
> 
> ```js
> this.audioRecorderPlayer.removeRecordBackListener()
> ```
> 
> Worked for me. I don't use that listener while recording, but iOS needs it.

Thanks, this is working
