### ISSUE TITLE
Does not play with local url

### ISSUE THREAD

**Issue by milesscherrer** [hyochan/react-native-audio-recorder-player#294]
When trying to play a local URL nothing is played. This worked in version 2 but the following happens in 3.0.2.

With a url:

`file:///Users/.../Library/Developer/CoreSimulator/Devices/.../data/Containers/Data/Application/.../Documents/newRecordedClip.mp3`

and the following call:

`const msg = await this.audioRecorderPlayer.startPlayer(url);
 console.log(msg);`
 
 the console logged path becomes:
 
 `file:///Users/.../Library/Developer/CoreSimulator/Devices/.../data/Containers/Data/Application/.../Library/Caches/file:///Users/.../Library/Developer/CoreSimulator/Devices/.../data/Containers/Data/Application/.../Documents/newRecordedClip.mp3
`

I get an incorrect path returned where the cache folder path is added before the custom path. External custom url:s work like before.

**Comment by hyochan** [comment]
Currently, this is not designed to support complex `file uri` since I've not yet had think of differentiating `iOS` and `android` for that.

How about using rn-fetch-blob as I've noted in the readme?

**Comment by milesscherrer** [comment]
Got it, solved it with a project specific workaround. Thanks!

**Comment by rene-tan-thoughtfull** [comment]
@milesscherrer , i'm also having the same issue. may i know how did you solve it?

**Comment by guzeradimaz** [comment]
+

**Comment by guzeradimaz** [comment]
same error
