### ISSUE TITLE
[SOLVED] Remote audio url sent from Android won't playback on iOS device

### ISSUE THREAD

**Issue by efstathiosntonas** [hyochan/react-native-audio-recorder-player#295]
### Version of react-native-audio-recorder-player
 `3.0.2`, react native: `0.63.4`
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Play remote audio files sent from android
### Actual behavior
If an Android device sends an audio message to an iOS device then the audio player won't play that file. This lib is being used in a chat room where users exchange audio messages.

### Steps to reproduce the behavior
 Recording function:

```
import { Dirs, FileSystem } from "react-native-file-access";

const onStartRecord = async () => {
    ReactNativeHapticFeedback.trigger(
      hapticTriggerType as HapticFeedbackTypes,
      hapticOptions
    );
    const path = Platform.select({
      ios: "remote_audio/remote_audio_message.m4a",
      android: `${Dirs.CacheDir}/remote_audio/remote_audio_message.m4a`
    });
    try {
      const audioSet: AudioSet = {
        AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
        AudioSamplingRateAndroid: 44100,
        AudioSourceAndroid: AudioSourceAndroidType.MIC,
        AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.medium,
        AVFormatIDKeyIOS: AVEncodingOption.aac,
        AVNumberOfChannelsKeyIOS: 2,
        OutputFormatAndroid: OutputFormatAndroidType.AAC_ADTS
      };
      const meteringEnabled = false;
      stopPlayer().catch((e) =>
        console.log(`error while stopping player of messages bubbles, error: ${e}`)
      );
      await FileSystem.mkdir(`${Dirs.CacheDir}/remote_audio`).catch((e) => console.log(e));
      await audioRecorderPlayer.startRecorder(path, audioSet, meteringEnabled);
      // @ts-ignore
      audioRecorderPlayer.addRecordBackListener((e: RecordBackType) => {
        setRecord({
          recordSecs: e.currentPosition,
          recordTime: audioRecorderPlayer.mmssss(Math.floor(e.currentPosition))
        });
      });
    } catch (e) {
      console.log(e);
    }
  };

```

While using version `2.7.0` it works like a charm. Upgrading to `3.0.2` won't play the remote audio file sent by an Android device with no errors on metro or xCode console. It will just sit there and wait after tapping "play" button.

Weird thing is that the audio files being sent from iOS can be played from the remote url just fine (on iOS device). Tried to change the `AudioEncoderAndroidType` and `OutputFormatAndroid` into different encoders but the issue persists.

On Android everything works as it should.

**Comment by hyochan** [comment]
I don't quiet understand the situation. Are you saying that the audio uploaded from the `android` to your backend is not playing from the `iOS`?

**Comment by efstathiosntonas** [comment]
Yes, and the audio file uploaded from iOS plays fine on both Android and iOS! When I try to play the file sent from Android it won't play.

**Comment by hyochan** [comment]
https://developer.android.com/reference/android/media/MediaRecorder.OutputFormat.html

Hmm.. Have you tried the `aac` format?

**Comment by efstathiosntonas** [comment]
If you mean `AAC_ADTS` this is what I'm using. It's really strange issue, forgot to mention I've tested it on both simulator and real device. I'll test what happens between two iOS devices.

**Comment by hyochan** [comment]
@efstathiosntonas Could you also specify the version of android? I am wondering if something is breaking in new Android device.

**Comment by efstathiosntonas** [comment]
@hyochan I'm using a Xiaomi Redmi Note 8 with android 10 (QKQ1.200113.002)

**Comment by hyochan** [comment]
@Larpoux Hey my friend. Do you have any idea on this issue?

**Comment by Larpoux** [comment]
Hi, guys,

No, I don't have any idea. AAC_ADTS is probably the only CODEC/FORMAT which is compatible both on Android and iOS.

If I understand correctly your sound follows 4 steps : 
- Creation of the file on Android
- Upload the file to the server
- Download the file to iOS
- Playback the file on ioS

One of those 4 steps is not OK.
I suggest that you : 
- download the file from your server and Probe it with a utility programme like FFmpeg.
- Create and upload a AAC_ADTS file to your server (without Android) and try to play it on iOS 

We will have a better idea which of these 4 steps is incorrect.

**Comment by hyochan** [comment]
@Larpoux Thanks for the reply 🙏

@efstathiosntonas Could you try out what is written above and come back?

**Comment by adrienGzc** [comment]
Hi,
Change `AAC_ADTS ` to `MPEG_4 `.

**Comment by efstathiosntonas** [comment]
Hi @hyochan, sorry for the reaaaally long delay, since rn 0.65 came out I think all users must upgrade to 3.x since 2.x is not building on Android so here I am 😄 

I'll run some tests today and I'll post the results. There's another user that I believe is facing the same [issue](https://github.com/hyochan/react-native-audio-recorder-player/issues/336#issuecomment-886707464) like me:

**Comment by efstathiosntonas** [comment]
@hyochan this file info from ffmpeg won't play:

```bash
Input #0, aac, from 'nhqodWzu1TXPISoxM1U1':
  Duration: 00:00:17.58, bitrate: 98 kb/s
  Stream #0:0: Audio: aac (LC), 44100 Hz, mono, fltp, 98 kb/s
```

while this is playing fine: 

```bash
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'rBumiLNskZfTorhVzs90':
  Metadata:
    major_brand     : M4A
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2021-08-20T11:55:28.000000Z
  Duration: 00:00:02.88, start: 0.000000, bitrate: 259 kb/s
  Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 100 kb/s (default)
    Metadata:
      creation_time   : 2021-08-20T11:55:28.000000Z
      vendor_id       : [0][0][0][0]

```

**Comment by ravis-farooq** [comment]
@efstathiosntonas I need to implement voice notes in React-Native-Gifted-Chat. How can we achieve that?

**Comment by efstathiosntonas** [comment]
@ravis-farooq check this repo out: https://github.com/GetStream/react-native-samples/tree/main/projects/WhatsAppClone#whatsapp-clone-using-react-native-and-stream-chat

this is the audio manager: https://github.com/GetStream/react-native-samples/blob/main/projects/WhatsAppClone/src/utils/AudioManager.ts

**Comment by ravis-farooq** [comment]
> @ravis-farooq check this repo out: https://github.com/GetStream/react-native-samples/tree/main/projects/WhatsAppClone#whatsapp-clone-using-react-native-and-stream-chat
> 
> this is the audio manager: https://github.com/GetStream/react-native-samples/blob/main/projects/WhatsAppClone/src/utils/AudioManager.ts
> 
> this is the audio player: https://github.com/GetStream/react-native-samples/blob/main/projects/WhatsAppClone/src/components/channel/VoiceMessageAttachment.tsx
> 
> I'm using [react-native-awesome-slider](https://github.com/alantoa/react-native-awesome-slider) for the audio track, it's super performant.

Thanks for replying i will check those 👍
