### ISSUE TITLE
Stop recorder fails on device with metering enabled

### ISSUE THREAD

**Issue by milesscherrer** [hyochan/react-native-audio-recorder-player#297]
When stopping the recorder I am getting the error:

`WARN Possible Unhandled Promise Rejection (id: 0):
Error: Faled to stop recorder`

Works on simulator but not on device (neither dev nor release).

### Version of react-native-audio-recorder-player
3.0.2

### Platforms you faced the error (IOS or Android or both?)
IOS (not sure abut android)

### Steps to reproduce the behavior

Microphone permissions in info.plist, accept by user.
Call startRecorder with meteringEnabled=true on device.

**Comment by milesscherrer** [comment]
Works when removing

`try recordingSession.setActive(false)`

But this will likely have other consequences?

**Comment by hyochan** [comment]
@milesscherrer Can't reproduce this in `Example` project. Could you try `rm -rf node_modudules` and reinstalling it?

**Comment by jcarriagc** [comment]
Where did you modify this? I have the same problem on IOS

> Works when removing
> 
> `try recordingSession.setActive(false)`
> 
> But this will likely have other consequences?

**Comment by milesscherrer** [comment]
Row 253 in RNAudioRecorderPlayer.swift

`if (audioRecorder != nil) {
            do {
                audioRecorder.stop()
                
                /*try recordingSession.setActive(false, options: .notifyOthersOnDeactivation)*/

                if (recordTimer != nil) {
                    recordTimer!.invalidate()
                    recordTimer = nil
                }

                resolve(audioFileURL?.absoluteString)
            /*} catch {
                reject("RNAudioPlayerRecorder", "Faled to stop recorder", nil)
            }*/
            }
        }`
        
        I do get some weird behaviour with the microphone chopping up audio playback with this hack.

**Comment by hyochan** [comment]
Fixed in `3.0.8`
