### ISSUE TITLE
Is it possible to play the cloud file?

### ISSUE THREAD

**Issue by Yandamuri** [hyochan/react-native-audio-recorder-player#298]
I have audio files in my server. Now, I am downloading them and then playing. is it possible to play with out downloading them?

### Platform

I want this behaviour in both Android and iOS

### Expected Behaviour
 
Cloud audios files should be played without downloading

### Actual behavior

Now, I am downloading and playing them.

**Comment by hyochan** [comment]
This can be done without downloading from 3.0.0

**Comment by hyochan** [comment]
Please see check the readme and v3 release note.
https://medium.com/dooboolab/react-native-audio-player-and-recorder-v3-7697e25cd07

**Comment by Yandamuri** [comment]
@hyochan This is great. When was the 3.0 released and is it stable version?

**Comment by hyochan** [comment]
The current version is `3.0.2` and this is tested and ok for production (I think)
