### ISSUE TITLE
Can't set full path to audio file on iOS

### ISSUE THREAD

**Issue by farwayer** [hyochan/react-native-audio-recorder-player#300]
react-native-audio-recorder-player 3.0.2

In 2.x version it was possible to specify full path to playing/recording audio file with `file://` prefix. In version 3.x only cache directory is supported.
2.x: https://github.com/hyochan/react-native-audio-recorder-player/blob/d780d7fc4bdafbb2d5612a8bdb3fb0efe20592db/ios/RNAudioRecorderPlayer.m#L144-L149
3.x: https://github.com/hyochan/react-native-audio-recorder-player/blob/7d6e3bd6d11430ae04544cb5f0ed1e864d8f26d7/ios/RNAudioRecorderPlayer.swift#L41-L46

**Comment by hyochan** [comment]
Try to use the rn fetch blob as provided in the readme

**Comment by farwayer** [comment]
I'm not sure it can help to record audio to specific file. Of course as workaround I can record audio to cache directory and then move the file to directory I want but it is ugly solution.

**Comment by hyochan** [comment]
@farwayer I understand your point. How do you like the `PR` in #301? I'll release this to `3.0.3`.

**Comment by farwayer** [comment]
@hyochan #301 has issue and raises an error https://github.com/hyochan/react-native-audio-recorder-player/issues/304
Correct change will be
```swift
-        } else if (path.contains("http")){
+        } else if (path.hasPrefix("http://") || path.hasPrefix("https://") || path.hasPrefix("file://")){
```

**Comment by farwayer** [comment]
Or event better:
```swift
} else if (path.range(of: #"\w*://"#, options: .regularExpression)) {
```

**Comment by hyochan** [comment]
Thanks for the update. I am not sure why in my `env`, error did not occur.

Also, I'd prefer the first one since the regular expression is not readable to everyone.

Next time please create a `PR`.
