### ISSUE TITLE
CocaPods could not find compatible Version for pod "RNAudioRecorderPlayer"

### ISSUE THREAD

**Issue by gulsher7** [hyochan/react-native-audio-recorder-player#303]
Specs satisfying the `RNAudioRecorderPlayer (from `../node_modules/react-native-audio-recorder-player`)` dependency were found, but they required a higher minimum deployment target.

**Comment by gulsher7** [comment]
when i changed ios version 10 to 11 then pod install successfully

**Comment by hyochan** [comment]
I think this is your RN project issue

**Comment by hyochan** [comment]
Related #308
