### ISSUE TITLE
Cannot assign value of type 'String' to type 'URL

### ISSUE THREAD

**Issue by gulsher7** [hyochan/react-native-audio-recorder-player#304]
can't able to make build after install this module please check i have attached two file please look into this. 

![Screenshot 2021-05-18 at 2 50 57 PM](https://user-images.githubusercontent.com/56266123/118626481-89f89f00-b7e8-11eb-9304-3b26035c1921.png)

![Screenshot 2021-05-18 at 2 50 47 PM](https://user-images.githubusercontent.com/56266123/118626505-8ebd5300-b7e8-11eb-8d75-8f4b99627e54.png)

**Comment by gulsher7** [comment]
unfortunately  i have uninstalled this module 😞

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/118649212-37d27080-b81e-11eb-853a-06db2a45d5ee.png)

I've just succeeded in the  `Example` project. Could you please compare to yours and see the differences? We need reproduction to fix the issue if this is a real issue.

Have you followed the readme and enabled the swift support?

**Comment by gulsher7** [comment]
i have already create swift file with header-bridge before using this module. i

![Screenshot 2021-05-18 at 5 51 27 PM](https://user-images.githubusercontent.com/56266123/118650345-f59b3600-b801-11eb-84a5-67544aefe61d.png)

**Comment by Maering** [comment]
I had the same issue as @gulsher7 and fixed it by changing 
```
} else if (path.contains("file")) {
    audioFileURL = path
} 
``` 

to 

```
} else if (path.contains("file")) {
    audioFileURL = URL.init(string: path)
} 
```

**Comment by farwayer** [comment]
Please check this two comments https://github.com/hyochan/react-native-audio-recorder-player/issues/300#issuecomment-843126474
