### ISSUE TITLE
CocoaPods could not find compatible versions for pod "RNAudioRecorderPlayer"

### ISSUE THREAD

**Issue by Haseeba393** [hyochan/react-native-audio-recorder-player#308]
I have made a fresh react native project to test react-native-audio-recorder-player working. I have used npm install react-native-audio-recorder-player to installl the library but while installing to ios side using pod install it is giving me this error:
![image](https://user-images.githubusercontent.com/41360976/118803716-25f3da80-b8bd-11eb-801a-88a825d74e48.png)

### Version of react-native-audio-recorder-player
3.0.5

### Version of React Native
0.63.4

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
The library should install on both for android and ios and will work correctly.

### Actual behavior
Installing the library on ios side giving error shown in above picture

**Comment by hyochan** [comment]
This support [ios platform `11.0`](https://github.com/hyochan/react-native-audio-recorder-player/blob/08f90ef405fb4e0946a58b15e6e929a8dfd17138/RNAudioRecorderPlayer.podspec#L13)

**Comment by hyochan** [comment]
Related #308

**Comment by Haseeba393** [comment]
Can you please let me know about those settings? and also will it affect other app or not?
