### ISSUE TITLE
addRecordBackListener parameter type issues

### ISSUE THREAD

**Issue by meeoh** [hyochan/react-native-audio-recorder-player#309]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

For `addRecordBackListener`, I copied the example but am still getting a type error. I tried adding the parameter type but its still not happy:

![image](https://user-images.githubusercontent.com/61977684/119019161-e5529a80-b96a-11eb-9e17-9073563183be.png)

**Comment by hyochan** [comment]
Looks like we need a contribution for that.
Would you like to go with it?

You can currently ignore this with `//@ts-ignore`

**Comment by meeoh** [comment]
https://github.com/hyochan/react-native-audio-recorder-player/pull/310
