### ISSUE TITLE
stopRecorder not working in functional component 

### ISSUE THREAD

**Issue by Aditya1942** [hyochan/react-native-audio-recorder-player#313]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Version of react-native-audio-recorder-player 
    "react-native-audio-recorder-player": "^3.0.2"

### Version of React Native
    "react-native": "0.64.0",

### Platforms you faced the error (IOS or Android or both?)
Android. not tested in ios

### Expected behavior
voice recording should stop 

### Actual behavior
recording still on and logged Already stopped

**Comment by hyochan** [comment]
Could you try the `Test` project? I've not experienced this. It should not matter with the functional component.

**Comment by Aditya1942** [comment]
> Could you try the `Test` project? I've not experienced this. It should not matter with the functional component.

yes i have test with a test project it doesn't work  with functional component

here is stop function i am using

`
 const onStopRecord = async () => {
      const result = await audioRecorderPlayer.stopRecorder();
      audioRecorderPlayer.removeRecordBackListener();
      setrecordSecs(0)
      console.log(result);
    };
  `

**Comment by hyochan** [comment]
I am suspecting, something rerenders your functional component before stopping.
Try to wrap this with `useCallback`.

It should not matter with the `functional` component theoretically.
Try to share your codes so someone can see your logical error.

**Comment by Aditya1942** [comment]
thank you so much brother it worked with useCallback 
here is the code 

for start recording
`
const onStartRecord = React.useCallback(async () => {
    if (Platform.OS === 'android') {
      try {
        const grants = await PermissionsAndroid.requestMultiple([
          PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
          PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
          PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
        ]);
        console.log('write external stroage', grants);
        if (
          grants['android.permission.WRITE_EXTERNAL_STORAGE'] ===
            PermissionsAndroid.RESULTS.GRANTED &&
          grants['android.permission.READ_EXTERNAL_STORAGE'] ===
            PermissionsAndroid.RESULTS.GRANTED &&
          grants['android.permission.RECORD_AUDIO'] ===
            PermissionsAndroid.RESULTS.GRANTED
        ) {
          console.log('permissions granted');
        } else {
          console.log('All required permissions not granted');
          return;
        }
      } catch (err) {
        console.warn(err);
        return;
      }
    }
    const audioSet: AudioSet = {
      AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
      AudioSourceAndroid: AudioSourceAndroidType.MIC,
      AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high,
      AVNumberOfChannelsKeyIOS: 2,
      AVFormatIDKeyIOS: AVEncodingOption.aac,
    };
    console.log('audioSet', audioSet);
    const uri = await audioRecorderPlayer.startRecorder(undefined, audioSet);
    audioRecorderPlayer.addRecordBackListener((e: RecordBackType) => {
      console.log('record-back', e);
      setrecordSecs(e.currentPosition);
      setrecordTime(audioRecorderPlayer.mmssss(Math.floor(e.currentPosition)));
    });
    console.log(`uri: ${uri}`);
  }, []);

`
for stop recording 
`
  const onStopRecord = React.useCallback(async () => {
    const result = await audioRecorderPlayer.stopRecorder();
    audioRecorderPlayer.removeRecordBackListener();
    setrecordSecs(0);
    console.log(result);
  }, []);
`
again thanks for you help really appreciated

**Comment by KrisLau** [comment]
Formatted @Aditya1942's code for reference

for start recording:
```
const onStartRecord = React.useCallback(async () => { 
    if (Platform.OS === 'android') { 
        try { 
            const grants = await PermissionsAndroid.requestMultiple([
                PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE, 
                PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE, 
                PermissionsAndroid.PERMISSIONS.RECORD_AUDIO, 
            ]);
            console.log('write external stroage', grants); 
            if ( grants['android.permission.WRITE_EXTERNAL_STORAGE'] === PermissionsAndroid.RESULTS.GRANTED && grants['android.permission.READ_EXTERNAL_STORAGE'] === PermissionsAndroid.RESULTS.GRANTED && grants['android.permission.RECORD_AUDIO'] === PermissionsAndroid.RESULTS.GRANTED ) { 
                console.log('permissions granted'); 
            } else { 
                console.log('All required permissions not granted'); 
                return; 
            }
        } catch (err) {
            console.warn(err);
            return; 
        } 
    } 
    const audioSet: AudioSet = { 
        AudioEncoderAndroid: AudioEncoderAndroidType.AAC, 
        AudioSourceAndroid: AudioSourceAndroidType.MIC, 
        AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high, 
        AVNumberOfChannelsKeyIOS: 2, AVFormatIDKeyIOS: AVEncodingOption.aac, 
    };
    console.log('audioSet', audioSet); 
    const uri = await audioRecorderPlayer.startRecorder(undefined, audioSet); 
    audioRecorderPlayer.addRecordBackListener((e: RecordBackType) => { 
        console.log('record-back', e);         
        setrecordSecs(e.currentPosition); 
        setrecordTime(audioRecorderPlayer.mmssss(Math.floor(e.currentPosition))); 
    }); 
    console.log(uri: ${uri}`);
}, []);
```
----------------
for stop recording:
```
const onStopRecord = React.useCallback(async () => {
     const result = await audioRecorderPlayer.stopRecorder();
     audioRecorderPlayer.removeRecordBackListener();
     setrecordSecs(0);
     console.log(result);
}, []);
```

**Comment by KrisLau** [comment]
@hyochan #442 I shared my code that is having issues here

**Comment by gagtic** [comment]
Hi, I am trying to implement a listener in the functional component, can anyone please tell me where they are importing audioRecorderPlayer from? 

Is there any codebase I can take a look at?

Thank you

**Comment by KrisLau** [comment]
> Hi, I am trying to implement a listener in the functional component, can anyone please tell me where they are importing audioRecorderPlayer from?
> 
> Is there any codebase I can take a look at?
> 
> Thank you

https://github.com/hyochan/react-native-audio-recorder-player/tree/main/Example

**Comment by nachogonzalezsibila** [comment]
Hi, I was having this same issue, and useCallback didn't solve it for me.

Instead, moving audioRecorderPlayer initialization outside of the component did it.

`import AudioRecorderPlayer from 'react-native-audio-recorder-player';`
`const audioRecorderPlayer = new AudioRecorderPlayer();`
`const yourComponent = () => {`
`...`
`}`

**Comment by ravis-farooq** [comment]
> https://github.com/hyochan/react-native-audio-recorder-player/tree/main/Example

I tried to use useCallback hook and even i moved const audioRecorderPlayer = new AudioRecorderPlayer(); outside of component but still problem persists, The component is re-rendering again and again


`


    const onStartRecord = useCallback(async () => {
    try {
      if (audioRecorderPlayer) {
        audioRecorderPlayer.stopPlayer();
        setIsPlaying('');
        audioRecorderPlayer.removePlayBackListener();
        setPlayTime('00:00:00');
        if (Platform.OS === 'android') {
          const grants = await PermissionsAndroid.requestMultiple([
            PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
            PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
            PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
          ]);

          console.log('write external stroage', grants);

          if (
            !(
              grants['android.permission.WRITE_EXTERNAL_STORAGE'] ===
                PermissionsAndroid.RESULTS.GRANTED &&
              grants['android.permission.READ_EXTERNAL_STORAGE'] ===
                PermissionsAndroid.RESULTS.GRANTED &&
              grants['android.permission.RECORD_AUDIO'] ===
                PermissionsAndroid.RESULTS.GRANTED
            )
          ) {
            console.log('All required permissions not granted');

            return false;
          }
        }

        const path = Platform.select({
          ios: `${dayjs().format('DDMMYYYY[at]HHmmss')}.m4a`,
          android: `${dirs.CacheDir}/${dayjs().format(
            'DDMMYYYY[at]HHmmss',
          )}.m4a`,
        });
        // const path = `${dayjs().format('DD-MM-YYYY[at]HH:mm:ss')}.aac`;

        const audioSet = {
          AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
          AudioSourceAndroid: AudioSourceAndroidType.MIC,
          AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high,
          AVNumberOfChannelsKeyIOS: 2,
          AVFormatIDKeyIOS: AVEncodingOption.aac,
          OutputFormatAndroid: OutputFormatAndroidType.AAC_ADTS,
        };
        const uri = await audioRecorderPlayer.startRecorder(path, audioSet);

        await audioRecorderPlayer.addRecordBackListener(e => {
          setRecordSecs(e.currentPosition);
          setRecordTime(
            audioRecorderPlayer.mmssss(Math.floor(e.currentPosition)),
          );
        });
        console.log(uri, 'URI');
      }
          } catch (err) {
            console.warn(err);
            return;
          }
     }, []);
  
  
  `

**Comment by SoySauceFor3** [comment]
Just want to add that this issue is also on ios. Using callback fixed this issue on my end.
