### ISSUE TITLE
startRecorder results on low volume on playback 

### ISSUE THREAD

**Issue by robertqin86** [hyochan/react-native-audio-recorder-player#314]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Version of react-native-audio-recorder-player
3.0.6

### Version of React Native
0.63.4

### Platforms you faced the error (IOS or Android or both?)
IOS - Working fine on Android and iOS Simulator. The problem can be replicated on an iPhone device. Might be related to https://stackoverflow.com/questions/28070773/swift-avaudiorecorder-records-very-quietly. 

### Expected behavior
Volume should not be decreased on playback

### Actual behavior
Volume dropped drastically during playback. It almost sounds muted.

### Steps to reproduce the behabior
I could replicate this on the example code. After you press record audio, when you press playback, the volume drops drastically. This issue does not occur with version 2 (2.7.0) of react-native-audio-recorder-player.

**Comment by hyochan** [comment]
I've just made some updates in `3.0.7` in #315.

How does this look like?
You may close this issue if it works fine.

P.S. It is hard for me to debug since I am not experiencing it.

**Comment by robertqin86** [comment]
Hi @hyochan , thanks so much for your prompt attention. I can confirm that `3.0.7` fixes the issue, so I'm closing this now. I'm still curious why it was working in `2.7.0` and below without the fix you made, and when it was written in objective c. 

Thanks once again!
