### ISSUE TITLE
react-native-audio-recorder-player:compileDebugKotlin

### ISSUE THREAD

**Issue by Rafay3198** [hyochan/react-native-audio-recorder-player#316]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

**Comment by hyochan** [comment]
Closing due to no template filled.

**Comment by ZeeshanAhmadKhalil** [comment]
I am facing the same problem any fix??

**Comment by ZeeshanAhmadKhalil** [comment]
I was facing the same issue:

![image](https://user-images.githubusercontent.com/41861952/147284396-a60c9835-a53e-49da-9460-a063ecf25dd1.png)

My issue was resolved by upgrading the Kotlin version as follows:

1) Goto `android/build.gradle`

2) Change kotlin version to `1.6.10` or the latest version

```
buildscript {
    ext {
        RNNKotlinVersion = "1.6.10" // <-- change here
        . . .
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10" <-- change here
        . . .
    }
}
```

Reference:
https://stackoverflow.com/a/67816693/9108471
