### ISSUE TITLE
Unable to create new folders with the path variable

### ISSUE THREAD

**Issue by itseramin** [hyochan/react-native-audio-recorder-player#320]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Version of react-native-audio-recorder-player
3.0.7
### Version of React Native
0.64.1
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Create folder at Caches folder for my audio files
### Actual behavior
Doesnt create new folders and fails to create the files with it
### Steps to reproduce the behavior
Idk if its a permission issue or not, but if i make a custom name to my file it works but if i want to shift the file into a new folder with the '/' char (myfolder/audifile.m4a) it doesnt do that...

**Comment by itseramin** [comment]
Worked around it by reading through the releases' changelogs, and found out about the whole `https://` `file://` prefixes for filenames. After that, the whole usage of the [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob) package made sense for path names, but it isn't maintained anymore, so i sticked with [react-native-fs](https://github.com/itinance/react-native-fs) for folder creation and path names. IMO the README should be more in-depth about how and why stuff is coded the way they are, also having an example in plain javascript should be a must. Sorry for being lazy by creating this issue, I'm fairly new to react-native and the whole multi-platform development...

**Comment by pierroo** [comment]
I don't mean to sound lazy either, but can you please share your final solution using react-native-fs @itseramin ?
That would be greatly appreciated, I'm trying to avoid rn-fetch-blob too :)

**Comment by itseramin** [comment]
> I don't mean to sound lazy either, but can you please share your final solution using react-native-fs @itseramin ? That would be greatly appreciated, I'm trying to avoid rn-fetch-blob too :)

```
const RNFS = require('react-native-fs');

...
const path = `file://${RNFS.DocumentDirectoryPath}/${id}`;
...
```

Idk even remember what was the issue here... but I just looked thru my old source files and found this^ hope I could help you out

**Comment by pierroo** [comment]
It certainly does help me, I couldn't find my way around the react-native-fs library, thank you for your help! :)
