### ISSUE TITLE
"isRecording: false" khi startRecorder trên IOS

### ISSUE THREAD

**Issue by chaudev** [hyochan/react-native-audio-recorder-player#322]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

**react-native-audio-recorder-player - version 3.0.7**

My code same 

`const onStartRecordIOS = async () => {
     try {
        const path = 'xnxx.m4a';
        await record.startRecorder(path);
        record.addRecordBackListener(e => {
             console.log(e);
        });
     } catch (e) {
          console.log(e);
    }
  };`

On **Android** worked. But on **IOS** console.log returns _{"currentMetering": 0, "currentPosition": 0, "isRecording": false}_. However, there is a file in the path and it is only 20kb. 

Please help me!

**Comment by hyochan** [comment]
It looks like it is related #320. Just passing `xnxx.m4a` will direct to `cacheDirectory` in default so you need to access actual file path `file://`. Or try to use library like `rn-fetch-blob` as we provided in `Example` project!

**Comment by chaudev** [comment]
i was tried `'file://' + RNFS.CachesDirectoryPath + '/' + 'xhel.m4a'` 
and `'file://' + RNFetchBlob.fs.dirs.CacheDir + '/' + 'xhel.m4a'` 
but they fail with **'isRecording: false'**

**Comment by hyochan** [comment]
Could you please try thr example proj and comeback?

**Comment by NapChen** [comment]
has the same issue ,when i try ` const dirs = RNFetchBlob.fs.dirs;
        console.log(dirs.CacheDir);
        const path = Platform.select({
            ios: 'file://' + dirs.CacheDir + '/' + fileName + '.m4a',
            android: dirs.CacheDir + '/' + fileName + '.mp3',
        });`
it worked for me
