### ISSUE TITLE
App Stopped working after installing .

### ISSUE THREAD

**Issue by NitinSidhu** [hyochan/react-native-audio-recorder-player#325]
Version of react-native-audio-recorder-player:- 3.0.8

Version of React Native: - 0.63.2

 Facing this problem on android

the app stops working, Please help

![Screenshot 2021-06-16 114418](https://user-images.githubusercontent.com/58940083/122167486-a98ef000-ce98-11eb-9a07-2d1f34fc5ba8.png)

**Comment by hyochan** [comment]
I think you've missed the `readme`

Please refer to https://github.com/hyochan/react-native-audio-recorder-player#breaking-changes
