### ISSUE TITLE
Swift compiler error upon package installation

### ISSUE THREAD

**Issue by dangtony98** [hyochan/react-native-audio-recorder-player#327]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Version of react-native-audio-recorder-player

3.0.8

### Version of React Native

0.64.0

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

Project should correctly compile upon package installation and completion of post-installation steps.

### Actual behavior

Encountered 2 Swift Compiler errors in RNAudioRecorderPlayer.swift:

- Type 'String' has no member 'playAndRecord' 
- Type 'String' has no member 'default'

### Steps to reproduce the behabior:

Install package and RN under specified versions; try to build the application.
<img width="884" alt="Screen Shot 2021-06-16 at 3 56 04 PM" src="https://user-images.githubusercontent.com/25857006/122284205-5bd7af00-cebb-11eb-918c-5bfbf1dbf541.png">
<img width="1009" alt="Screen Shot 2021-06-16 at 3 56 26 PM" src="https://user-images.githubusercontent.com/25857006/122284257-68f49e00-cebb-11eb-9657-fb2c0fc165c2.png">

**Comment by hyochan** [comment]
Could you provide your XCode version? I am not sure why this is not happening on my side

**Comment by dangtony98** [comment]
XCode version is 12.5!

**Comment by dangtony98** [comment]
Update: It seems that everything works from a fresh RN project build as expected; however, the error persists when trying to integrate the package with an existing project. Will keep debugging!

**Comment by dangtony98** [comment]
Update: Managed to fix the error by converting the project from Swift 4 to Swift 5 and updating the Swift Compiler Language Version to 5. Closing.
