### ISSUE TITLE
when play audio,e.duration != e.currentPosition

### ISSUE THREAD

**Issue by NapChen** [hyochan/react-native-audio-recorder-player#328]
### Version of react-native-audio-recorder-player
3.0.9
### Version of React Native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
ios
### Expected behavior
when play audio,duration and currentPosition will equals
### Actual behavior
e.duration !=e.currentPosition at end of the audio
### Steps to reproduce the behabior
There's a certain probability of that happening
![image](https://user-images.githubusercontent.com/19644794/122316825-1238a400-cf4f-11eb-9277-5ff634b9edb4.png)

**Comment by NapChen** [comment]
I guess this issue is related to  https://github.com/hyochan/react-native-audio-recorder-player/issues/235

**Comment by NapChen** [comment]
it is possible to auto stop the player and  set a callback fun when the audio is playing to the end, then we don't need to stop player manualy

**Comment by hyochan** [comment]
> it is possible to auto stop the player and set a callback fun when the audio is playing to the end, then we don't need to stop player manualy

Could you give `PR` for this?

**Comment by NapChen** [comment]
> > it is possible to auto stop the player and set a callback fun when the audio is playing to the end, then we don't need to stop player manualy
> 
> Could you give `PR` for this?

I don't understand a word about Swift

**Comment by hyochan** [comment]
> > > it is possible to auto stop the player and set a callback fun when the audio is playing to the end, then we don't need to stop player manualy
> > 
> > 
> > Could you give `PR` for this?
> 
> I don't understand a word about Swift

This still can be handled in the `typescript` wide in `index.ts`

**Comment by joeljerushan** [comment]
> it is possible to auto stop the player and set a callback fun when the audio is playing to the end, then we don't need to stop player manualy

Wish this feature available to this package,

**Comment by meeoh** [comment]
Heres a PR that auto stops the player on completion https://github.com/hyochan/react-native-audio-recorder-player/pull/353

**Comment by rafalzawadzki** [comment]
What I've noticed while testing this issue is that the audio duration is different with each play. This seems to affect only files played from a URL, the duration of local file is correct (at least one just recorded by the lib).

```
Local file duration: 2275.5555555555557

Same file remote play 1: 6037.188208616781
Same file remote play 2: 4272.471655328798
Same file remote play 3: 3529.433106575964
Same file remote play 4: 4272.471655328798
```

With measured file duration being always longer than the actual length there is obviously no way of tracking the playback progress correctly :)

**Comment by jkyoo82** [comment]
audioRecorderPlayer.addPlayBackListener(async e => {
        let position = e.currentPosition;
        let duration = e.duration;

        setPlayTime(position);
        setDurationTime(duration);

       // progress bar 
       let cale = (position / duration) * (scaleWidth * 260);
        setProgress(cale);

        if (position === duration) {
          setIsPlaying(false);
          //setPlayTime(0);
          //setProgress(0);
        }
      });

it's work me.
