### ISSUE TITLE
upgrade to use kotlin plugin make apk release size 35M+ larger 

### ISSUE THREAD

**Issue by ivanzhang2** [hyochan/react-native-audio-recorder-player#333]
follow post install instructions, add 
`kotlinVersion = '1.5.0' `
and 
`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.0"`
then build release apk, any way, it will increate apk size about 35M+

this my be issue of android kotlin plugin make any apk release size bigger,  even it was 2M, it will increase 35M+ 
see releated post 
https://stackoverflow.com/questions/59368298/apk-file-size-increased-after-using-kotlin-in-android-project

suggestion:
can we still build with java? 

### Version of react-native-audio-recorder-player
lates 3.0.10

### Version of React Native
RN 0.64.2

### Platforms you faced the error (IOS or Android or both?)
android

### Expected behavior
before yarn add react-native-audio-recorder-player and enable kotlin ,my app release apk size is about 40M
### Actual behavior
now it is 78M+

### Steps to reproduce the behabior
build release apk will see

**Comment by hyochan** [comment]
Could you verify this again with analyzer? I think you may follow https://medium.com/androiddevelopers/making-the-most-of-the-apk-analyzer-c066cb871ea2,

I don't think this will increase 35mb.. with just enabling kotlin

**Comment by ivanzhang2** [comment]
@hyochan  yes, finally, we re-enable kotlin, jiust downgrade minSdkVersion from 24 to 21 (we dont need audio pause and resume feature),  and use latest version, everything is fine. 

i think we can close this issue,  let this be a knowledge share for us ...

**Comment by ivanzhang2** [comment]
FYI, we reduced our APK size from 79M to 35M ...

**Comment by hyochan** [comment]
@ivanzhang2 Thanks for letting me know :pray: 
Let's think about handling `minSdk` :thinking:

**Comment by yxy** [comment]
face the same problem here. :(
just downgrade minSdkVersion to 21, solved it.
