### ISSUE TITLE
Consistent crash after specific commands

### ISSUE THREAD

**Issue by meeoh** [hyochan/react-native-audio-recorder-player#340]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Version of react-native-audio-recorder-player
3.0.11

### Version of React Native
0.64.0

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
App does not crash

### Actual behavior
App crashes consistently

### Steps to reproduce the behaviour
1. Have an `audioRecorderPlayer`
2. Play (either local, or from URL).
3. Pause
4. Play
5. Stop

On stop, the app will crash

https://user-images.githubusercontent.com/61977684/123553988-08cbea80-d74c-11eb-8a27-30938f33eeee.mov

Crash log:
[crash_log.txt](https://github.com/hyochan/react-native-audio-recorder-player/files/6722371/crash_log.txt)

**Comment by hyochan** [comment]
Thanks for the issue and specific detail. I think #341 will solve the problem.

**Comment by meeoh** [comment]
Confirmed fixed in #341
