### ISSUE TITLE
Help wanted for Swift Bridging 

### ISSUE THREAD

**Issue by ravi0the0sun** [hyochan/react-native-audio-recorder-player#342]
### Version of react-native-audio-recorder-player
"react-native-audio-recorder-player": "^3.0.11",

### Version of React Native
"react-native": "^0.64.1",
### Platforms you faced the error (IOS or Android or both?)
IOS

I just want to know how the bridging header works as i tried this [link](https://stackoverflow.com/questions/31716413/xcode-not-automatically-creating-bridging-header) from `README.md` where i tried to create a header file `ProjectName-Bridging-Header.h` which didnt work then i looked at the `Example` where you used `SwiftBridge.swift` and also copied the `Build Settings` for `Swift Compiler` which worked for me. can you explain how this works? 

Thank you for your constant support in this project.

**Comment by hyochan** [comment]
Normally it will automatically ask you to generate it when you create swift file

**Comment by ravi0the0sun** [comment]
yeah but i dont have the Bridging header file instead i have the  `SwiftBridge.swift` is there a difference?

**Comment by hyochan** [comment]
I think you should [manually add a bridging header](https://mycodetips.com/ios/manually-adding-swift-bridging-header-1290.html) if the automatic popup does not appear.

Closing this issue for now since it does not relate to the library itself.

**Comment by ravi0the0sun** [comment]
Thanks for that but do i need to import anything inside the header file?

**Comment by hyochan** [comment]
> Thanks for that but do i need to import anything inside the header file?

Nope you don't

**Comment by eramudeep** [comment]
i have already added the bridging header for another library. do I still need to create another one .?
