### ISSUE TITLE
How to fix react-native not recording audio

### ISSUE THREAD

**Issue by Fatih124** [hyochan/react-native-audio-recorder-player#343]
Hello I use to react native audio recorder player package for record audio. No sound is recorded even though all permissions are granted. This is the code I'm using. I edited the androidmanifest.xml file. However, it still does not register. When the recording button is clicked the computer's microphone is active, but the application does not record sound

const audioRecorderPlayer = new AudioRecorderPlayer();

export default class App extends Component {
  constructor() {
    super();
    this.state = {
      time: '00:00:00',
      start: false,
      url: '',
      PlayTime: '00:00:00',
      PlayDuration: '00:00:00',
      Play: false
    }
  }

  onStart = async  () => {
    const result  = await audioRecorderPlayer.startRecorder();
    audioRecorderPlayer.addRecordBackListener((e)=>{
      this.setState({
        start:true,
        time:audioRecorderPlayer.mmssss(Math.floor(e.current_position))
      })
      return;
    });
  };

  onStop = async () => {
    const result = await audioRecorderPlayer.stopRecorder();
    audioRecorderPlayer.removeRecordBackListener();
    this.setState({url: result});
  };

  play = async () => {
    const result = await audioRecorderPlayer.startPlayer();
    audioRecorderPlayer.addPlayBackListener((e)=>{
      if (e.current_position == e.duration){
        audioRecorderPlayer.stopPlayer();
      }
      this.setState({
        play:true,
        playTime:audioRecorderPlayer.mmssss(Math.floor(e.current_position)),
        playDuration:audioRecorderPlayer.mmssss(Math.floor(e.duration)),
        });
      return;
    });
  };

  pause = async () => {
    this.setState({
      play: false
    })
    await audioRecorderPlayer.pausePlayer();
  };

  render() {
    return (
      <View>
        <Text>{this.state.time}</Text>
        <TouchableOpacity
          onPress={(!this.state.start) ? this.onStart : this.onStop}>
          <Icon color={(!this.state.start) ? 'black' : 'red'} name={(!this.state.start) ? "microphone" : "microphone-slash"} size={50} />
        </TouchableOpacity>

        {
          this.state.url != '' &&
          <View>
            <Text>{this.state.playTime} - { this.state.playDuration}</Text>
            <TouchableOpacity onPress={(!this.state.play) ? this.play : this.pause}>
              <Text>{!this.state.play ? 'Play ' : 'Stop'}</Text>
            </TouchableOpacity>
          </View>
        }
      </View>
    )
  }
}

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/123723723-f7a6e900-d8c5-11eb-9cc4-2011aa42574f.png)

It looks like you've not followed the above readme.

**Comment by Fatih124** [comment]
Hello I used to this code block and I edit AndroidManifest.xml file for permission access. But the application has access to the microphone does not record sound

**Comment by Fatih124** [comment]
Hello I used to this code block and I edit AndroidManifest.xml file for permission access. But the application has access to the microphone does not record sound

``

**Comment by Fatih124** [comment]
> ![image](https://user-images.githubusercontent.com/27461460/123723723-f7a6e900-d8c5-11eb-9cc4-2011aa42574f.png)
> 
> It looks like you've not followed the above readme.

Hello I used to this code block and I edit AndroidManifest.xml file for permission access. But the application has access to the microphone does not record sound
