### ISSUE TITLE
A problem occurred evaluating project ':react-native-audio-recorder-player'.

### ISSUE THREAD

**Issue by Alexanderwags** [hyochan/react-native-audio-recorder-player#345]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

**Comment by Alexanderwags** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/26121628/123840137-fb456a80-d8db-11eb-969d-b5580cec0498.png)

**Comment by hyochan** [comment]
Looks like you've not followed the readme
![image](https://user-images.githubusercontent.com/27461460/124290875-ecd2a980-db8e-11eb-880a-1edb9dc66cb7.png)

**Comment by Alexanderwags** [comment]
> Looks like you've not followed the readme
> ![image](https://user-images.githubusercontent.com/27461460/124290875-ecd2a980-db8e-11eb-880a-1edb9dc66cb7.png)

Thanks very much , @hyochan.
