### ISSUE TITLE
Does not Exist Error 

### ISSUE THREAD

**Issue by Fatih124** [hyochan/react-native-audio-recorder-player#350]
I have done all the steps in the installation guide. I made all the settings, but when I run the application, android studio gives such an error

![error](https://user-images.githubusercontent.com/57414072/124517377-7d59f580-ddec-11eb-8679-a2c293a7729b.png)

**Comment by hyochan** [comment]
I looks like your project is not able to read Kotlin. Have you followed that step?

**Comment by Fatih124** [comment]
Yes I followed all steps

![image](https://user-images.githubusercontent.com/57414072/124663422-bbb9e800-deb2-11eb-8665-06fd1e048709.png)

**Comment by pranatha** [comment]
same here, have you solved this issue?

**Comment by Fatih124** [comment]
> same here, have you solved this issue?

No I haven't figured it out yet

**Comment by hoanglehaithanh** [comment]
I got this issue and found the solution after inspecting the `node_modules` folder:
Change
```kotlin
import com.dooboolab.RNAudioRecorderPlayerPackage;
```

to 
```kotlin
import com.dooboolab.audiorecorderplayer.RNAudioRecorderPlayerPackage;
```

**Comment by hyochan** [comment]
Oops, just fixed the readme in https://github.com/hyochan/react-native-audio-recorder-player/commit/3913e6a9418677e54ebf8cffe23cf61ef9f8d1bb.

Sorry for inconvenience 🙏
