### ISSUE TITLE
Stop record that is paused avoid to pause the next one

### ISSUE THREAD

**Issue by jeremy-habit** [hyochan/react-native-audio-recorder-player#361]
### Version of react-native-audio-recorder-player
    "react-native-audio-recorder-player": "^3.1.0",

### Version of React Native
    "react-native": "0.64.1",

### Platforms you faced the error (IOS or Android or both?)
BOTH
### Expected behavior
StopRecord after pauseRecord should not causing bug

### Actual behavior
PauseRecord before stopRecord causing problem

### Steps to reproduce the behavior
1 - start record
2 - pause record
3 - stop record
4 - start record
5 - pause record ==> still recording

**Comment by hyochan** [comment]
Can this be reproduced in our example project?
I am not getting this.
