### ISSUE TITLE
Error occured during initiating recorder

### ISSUE THREAD

**Issue by Debuggernaut** [hyochan/react-native-audio-recorder-player#374]
Loaded up the example project from this repo, ran "yarn install", then hit an error, ran "pod install" in the ios folder to get past it, ran "yarn ios" to build and load up the sample app in the simulator.

Hitting record showed a popup asking for microphone permission.  I clicked OK, then the app threw the error below.  It created a file, but the file it created is only 28 bytes

>  LOG  Running "RNAudioRecorderPlayer" with {"rootTag":1,"initialProps":{}}
>  LOG  audioSet {"AVEncoderAudioQualityKeyIOS": 96, "AVFormatIDKeyIOS": "aac", "AVNumberOfChannelsKeyIOS": 2, "AudioEncoderAndroid": 3, "AudioSourceAndroid": 1}
>  WARN  Possible Unhandled Promise Rejection (id: 0):
> Error: Error occured during initiating recorder

### Version of react-native-audio-recorder-player
RNAudioRecorderPlayer (3.1.2)

### Version of React Native
sorry buddy, I'm too much of a noob to know how to get this.. my podfile.lock file says this though:

>   - React (0.64.1):
>     - React-Core (= 0.64.1)

### Platforms you faced the error (IOS or Android or both?)

ios

### Expected behavior

Audio would be recorded into the file

### Actual behavior

The file is empty

### Steps to reproduce the behavior

Reprod in example project to eliminate as much PEBKAC as possible

[errorLog.txt](https://github.com/hyochan/react-native-audio-recorder-player/files/6979273/errorLog.txt)
[Podfile.lock.zip](https://github.com/hyochan/react-native-audio-recorder-player/files/6979275/Podfile.lock.zip)

**Comment by Debuggernaut** [comment]
I tried a couple of different filenames.  The default cache path file is created and just 28 bytes.  I also tried passing in the documents directory and "test.m4a", this file was created as well but was only 28 bytes.  I hamfistedly tracked the error message down to here, FWIW:  https://github.com/hyochan/react-native-audio-recorder-player/blob/master/ios/RNAudioRecorderPlayer.swift#L222

**Comment by Debuggernaut** [comment]
Turns out I ran afoul of this old bug:  https://developer.apple.com/forums/thread/650741

Updating Xcode fixed it for me

**Comment by skam22** [comment]
@Debuggernaut ran into the same issue and the swift file that you pointed at helped me to solve the problem.

if you scroll to line 37 you'll see how the fileURL is determined:

`func setAudioFileURL(path: String) {
        if (path == "DEFAULT") {
            let cachesDirectory = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
            audioFileURL = cachesDirectory.appendingPathComponent("sound.m4a")
        } else if (path.hasPrefix("http://") || path.hasPrefix("https://") || path.hasPrefix("file://")) {
            audioFileURL = URL(string: path)
        } else {
            let cachesDirectory = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
            audioFileURL = cachesDirectory.appendingPathComponent(path)
        }
    }
`

from that we can determine that a full file path must have the prefix of file:// , or alternatively if you wish to use the default cache directory with a custom file name you simply pass in the string of the file name (without directory).

the following two examples are working for me:

audioRecorderPlayer.startRecorder('customName.m4a')
audioRecorderPlayer.startRecorder(`file://${RNFS.CachesDirectoryPath}/customName.m4a`

**Comment by mdtechcs** [comment]
I am still getting this issue with latest library version. what was the resolution for this issue? @hyochan

**Comment by mdtechcs** [comment]
Also getting the same error in example https://github.com/hyochan/react-native-audio-recorder-player/tree/master/Example
@hyochan 


simulator os: iOS 14.1
xcode version: Version 12.1

**Comment by Debuggernaut** [comment]
Hey @mdtechcs , there were a few problems I ran into: 

- I was using the wrong file path
- Audio was misconfigured in my simulator
- I coincidentally downloaded the simulator during a brief time when there was a bug that broke audio in it
- Audio was screwed up on my whole desktop computer by an outdated audio plugin I had installed

I figured out most of these problems by getting a plain iOS Swift audio recording "Hello, World!" app running.  Once it was working, I was able to fix the react native audio library in my project pretty quickly

**Comment by Lordhacker756** [comment]
@mdtechcs Was your problem resolved?
I'm also facing the same issue despite following all the instructions and also trying to implement all the available solutions in previous issues
