### ISSUE TITLE
stopRecorder not working

### ISSUE THREAD

**Issue by aneena-thomas** [hyochan/react-native-audio-recorder-player#377]
stopRecorder not working it shows already stopped working.

Version: 3.1.2

@hyochan

**Comment by dbarner1** [comment]
Same here

**Comment by Billalkhn** [comment]
stopRecorder Function is working properly.
Outside the component, add const audioRecorderPlayer = new AudioRecorderPlayer(); to make this work. As a result, the component will appear like this.

for Functional Component: 

const audioRecorderPlayer = new AudioRecorderPlayer();

const App = () => {
  const [isLoggingIn, setIsLoggingIn] = useState(false);
  return(
               ...
  )
}
  
For Class component:

inside the constructor

constructor(props) {
      super(props);
      this.state = {
      };
      this.audioRecorderPlayer = new AudioRecorderPlayer();
    }

**Comment by aneena-thomas** [comment]
@Billalkhn Thanks for the reply, it's working now. I have added this line 

const audioRecorderPlayer = new AudioRecorderPlayer();

inside the function.

**Comment by ksielyov** [comment]
Same. I just copy from documentation

**Comment by mschouhan123** [comment]
Please refer the link to get the solution audio https://stackoverflow.com/a/77155779/15204127
