### ISSUE TITLE
Unable to stop recording if useState is used

### ISSUE THREAD

**Issue by sankomil** [hyochan/react-native-audio-recorder-player#385]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Steps to reproduce the behavior

- Create RN app
- Add recorder player library
- Create a component that works something like this:
```tsx
import React, { useState } from "react";
// import statements

export const RecorderTest = () => {
  const [isRecording, setIsRecording] = useState(false);

  return (
    <TouchableOpacity
      onPress={() => {
        if (isRecording) {
          onStopRecord();
        } else {
          setIsRecording(true);
          onStartRecord();
        }
      }}
    >
      {isRecording ? (
        <PauseIcon />
      ) : (
        <RecordIcon />
      )}
    </TouchableOpacity>
  );
};
```
- Press `RecordIcon`
- Press `PauseIcon`

I understand that the issue might have something to do with rerender but is there a way to implement a countdown or change the icon without causing issues with the recorder?

**Comment by delltrak** [comment]
**Am facing the same problem. did you find way to fix it ?**

**Comment by sankomil** [comment]
@delltrak I was able to resolve it by splitting everything into different components. So the actual recorder was in the parent component while I created a new component for the timer that was updated based on the values passed to it from the child and used `useState` to keep updating its values. This way only the child timer component updates without affecting the parent and so I am able to stop the recording.

**Comment by rf1804** [comment]
> @delltrak I was able to resolve it by splitting everything into different components. So the actual recorder was in the parent component while I created a new component for the timer that was updated based on the values passed to it from the child and used `useState` to keep updating its values. This way only the child timer component updates without affecting the parent and so I am able to stop the recording.

@sankomil Can you please share your code, how you made it work?

**Comment by rf1804** [comment]
Finally resolved the issue
This worked for me

https://github.com/hyochan/react-native-audio-recorder-player/issues/377#issuecomment-904537673

**Comment by kyeyunedaniel** [comment]
> Finally resolved the issue This worked for me
> 
> [#377 (comment)](https://github.com/hyochan/react-native-audio-recorder-player/issues/377#issuecomment-904537673)

Great.. this worked for me as well
