### ISSUE TITLE
Startplay from specific time

### ISSUE THREAD

**Issue by ehuamaniquispe** [hyochan/react-native-audio-recorder-player#395]
Sorry for this question, maybe it's something very easy.

How can I startPlay from a specific time(seconds or milliseconds)

thank you

**Comment by Vivaan7** [comment]
@ehuamaniquispe  you can use seek player for same thing check about seek player

**Comment by ehuamaniquispe** [comment]
Thank you very much for your answer. I had tried seek method before with milliseconds as a parameter but it didn't work. then I tried with seconds and it worked, thank you.

// actually it seeks 4000 seconds
onStatusPress = async (e) => {
   this.audioRecorderPlayer.seekToPlayer(4000); // in miliseconds
   this.onStartPlay();
 };

// actually it seeks 4 seconds
onStatusPress = async (e) => {
   this.audioRecorderPlayer.seekToPlayer(4); // in seconds
   this.onStartPlay();
 };
