### ISSUE TITLE
Remove listener and stop recording don't work

### ISSUE THREAD

**Issue by realfelixyu** [hyochan/react-native-audio-recorder-player#412]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Version of react-native-audio-recorder-player
3.3.2

### Version of React Native
0.63

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
When I start recording and add a record listerner recording should start successfully. When I stop the recorder and remove the listener, the listener callback shouldn't be called anymore.

### Actual behavior
Starting the recording works fine and the callback is getting called but removing the listener doesn't stop the callback from getting called, it looks like the recording isn't even stopped as the data passed into the listener callback has 'isRecording' set to true.

### Steps to reproduce the behabior
Start a recorder with a listener. Stop the recorder and remove the listener.

### CODE

  const startRecording = async () => {
    recordButtonRef.current.setNativeProps({
      disabled: true
    })
    const result = await audioRecorderPlayer.startRecorder();
    audioRecorderPlayer.addRecordBackListener((e) => {
      console.log("\n e: " + JSON.stringify(e))
      setAudioState({
        recordSecs: e.currentPosition,
        recordTime: audioRecorderPlayer.mmssss(
          Math.floor(e.currentPosition),
        ),
      });
      return;
    });
    recordButtonRef.current.setNativeProps({
      disabled: false
    })
    setRecordingVoice(true)
  };

  const stopRecording = async () => {
    recordButtonRef.current.setNativeProps({
      disabled: true
    })
    console.log("Stop record pressed")
    
    const result = await audioRecorderPlayer.stopRecorder();
    audioRecorderPlayer.removeRecordBackListener();
    setAudioState({
      recordSecs: 0,
    });
    setRecordingVoice(false)
    recordButtonRef.current.setNativeProps({
      disabled: false
    })
  };

**Comment by realfelixyu** [comment]
It looks like the fix is to wrap the start record and stop record function in a useCallback

**Comment by LavaRiddle** [comment]
This helped me a bunch, cheers, makes sense actually when you think about it!
