### ISSUE TITLE
Change audio quality in android and ios

### ISSUE THREAD

**Issue by Monisankarnath** [hyochan/react-native-audio-recorder-player#421]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Platforms you faced the error (IOS or Android or both?) : Both

I wish to edit the file quality to reduce the file size so i tried the audioset similar to this :

import AudioRecorderPlayer from 'react-native-audio-recorder-player';

const audioRecorderPlayer = new AudioRecorderPlayer();

const audioSet = {
        AudioEncoderAndroid: audioRecorderPlayer.AudioEncoderAndroidType.AAC,
        AudioSourceAndroid: audioRecorderPlayer.AudioSourceAndroidType.MIC,
        AVModeIOS: audioRecorderPlayer.AVModeIOSOption.measurement,
        AVEncoderAudioQualityKeyIOS: audioRecorderPlayer.AVEncoderAudioQualityIOSType.high,
        AVNumberOfChannelsKeyIOS: 2,
        AVFormatIDKeyIOS: audioRecorderPlayer.AVEncodingOption.aac
    };
await audioRecorderPlayer.startRecorder(null, audioSet);

But the audioRecorderPlayer doesn't have anything like AudioEncoderAndroidType. What should I do to meet my requirements?

**Comment by rmesquit** [comment]
You could try using a different Audio Encoder Android Type -- the options are:

  DEFAULT = 0,
  AMR_NB,
  AMR_WB,
  AAC,
  HE_AAC,
  AAC_ELD,
  VORBIS,

**Comment by hyochan** [comment]
Closes due to already covered.
