### ISSUE TITLE
Example app not working

### ISSUE THREAD

**Issue by rishabmahesh** [hyochan/react-native-audio-recorder-player#429]
I cloned the repo into my computer and did the following steps: -

1. cd Example
2. npm start
3. I opened a separate terminal and typed "npm run android" but I got an error saying "node_modules" not found. When I tried "npm i", this is the error I get: -

![image](https://user-images.githubusercontent.com/40054912/160299087-7d19aa6b-cbdb-4275-8dc1-638d4f390e02.png)

Can you please tell me if I did any incorrect steps, or where I am going wrong?

**Comment by mantusuff420** [comment]
If you want to Install it using yarn then there will be no error `yarn install`

If you want to Install it using npm like this `npm i --legacy-peer-deps`

**Comment by hyochan** [comment]
Closing since it is actually working.
