### ISSUE TITLE
Ios issue unhandled promise rejection on startRecorder not recording 

### ISSUE THREAD

**Issue by VirenV496** [hyochan/react-native-audio-recorder-player#436]
I was a implementing a audio feature using this Library  now on Android it's fine working as expected 

now when I started implementing in ios I was getting a one issue 

Unhandled promise rejection warning onstartRecorder
Whenever I invoke the function it won't record anything

This issue I'm only facing with ios only 

Current version react-native audio recorder player 3.4.0 tried with older version as well
React native version 0.64

How to reproduce
Invoking OnstartRecord  function 

Help me out here 

Thanks 

 onStartRecord = async () => {
       const path = 'audio.m4a';
       const audioSet = {
           AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
           AudioSourceAndroid: AudioSourceAndroidType.MIC,
           AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high,
           AVNumberOfChannelsKeyIOS: 2,
           AVFormatIDKeyIOS: AVEncodingOption.aac,
        };
        const meteringEnabled = false;

        let uri;
        
        try {
            uri = await this.audioRecorderPlayer.startRecorder(path, audioSet);
        } catch (e) { console.log("ERR audioRecorderPlayer.startRecorder: ", e) }
        this.audioRecorderPlayer.addRecordBackListener((e) => {
            setState(state => ({
                ...state,
                recordSecs: e.currentPosition,
                recordTime: audioRecorderPlayer.mmssss(
                    Math.floor(e.currentPosition),
                ),
			}));
            return;
		});
		console.log("uri: ", uri);
	};

this is the error i'm getting 
Possible Unhandled Promise Rejection (id: 2):
TypeError: null is not an object (evaluating 'RNAudioRecorderPlayer.startRecorder')

**Comment by gagtic** [comment]
The same thing happening here, using an M1 Mac. Same error on iOS.

 [Error: Error occured during initiating recorder]

**Comment by GerhardKotze** [comment]
Experiencing the same

**Comment by VirenV496** [comment]
> any solution here?

i did wasted a lot time to this library instead of wasting time on this library

**Comment by KrisLau** [comment]
@fukemy @GerhardKotze @gagtic  Did you guys ever figure it out? I tried `react-native-sound-recorder` and was having errors as well

**Comment by cj-hnadeem** [comment]
`uri = await this.audioRecorderPlayer.startRecorder(undefined, audioSet);`

Making the audio file path undefined worked for me.

**Comment by AscendAI** [comment]
I ran into this problem as well. @cj-hnadeem's solution fixed it for me. And following the file path we get when we pass undefined path, when i pass in a path of the same format, it works as well.
The path format should be like
```ts
  const recordingDir = `${
      dirs.CacheDir
  }/recordings/${new Date().getTime()}`;
  const path = Platform.select({
      ios: `${recordingDir}.m4a`,
      android: `${recordingDir}.mp3`,
  });
```
