### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by fukemy** [hyochan/react-native-audio-recorder-player#441]
AILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/vedax/Desktop/.../node_modules/react-native-audio-recorder-player/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-audio-recorder-player'.
> Plugin with id 'kotlin-android' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-audio-recorder-player'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by vanGalilea** [comment]
Same here, I'm using RN 0.68.1, might be the issue?

**Comment by cryptoalex** [comment]
+1, same issue

**Comment by hssdiv** [comment]
I think adding:

classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"

into node_modules > react-native-audio-rcorder-player > android > build.gradle
(below classpath 'com.android.tools.build:gradle:4.2.2')

might help

**Comment by fukemy** [comment]
thank, but i removed this lib due to other lib useful and fast response, not like this lib

**Comment by AsteriskZuo** [comment]
> thank, but i removed this lib due to other lib useful and fast response, not like this lib

Which bank did you change to, please?

**Comment by AsteriskZuo** [comment]
kotlinVersion = '1.6.10'
classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")

ref: #345 

https://central.sonatype.dev/artifact/org.jetbrains.kotlin/kotlin-gradle-plugin/1.8.0-RC2
