### ISSUE TITLE
`Error occured during initiating recorder`

### ISSUE THREAD

**Issue by KrisLau** [hyochan/react-native-audio-recorder-player#442]
### Version of react-native-audio-recorder-player
3.4.0

### Version of React Native
0.64.3

### Platforms you faced the error (IOS or Android or both?)
iOS (didn't try on Android)

### Expected behavior
Start recording and callbacks should be returning the current recording length

### Actual behavior
Getting error: `Error occured during initiating recorder`

### Steps to reproduce the behavior
Doesn't trigger error in snack but does in my project. Tested on an iOS simulator
https://snack.expo.dev/@kris_lau/rude-truffle

**Comment by KrisLau** [comment]
@hyochan

**Comment by duchunter** [comment]
I'm having the same issue on iOS emulator, but it's working fine on real device

**Comment by KrisLau** [comment]
Ok I'll test it out!

**Comment by KrisLau** [comment]
@duchunter Yup testing on a real device fixed it!

**Comment by vygandas** [comment]
@KrisLau making it work on a real device doesn't sound like a fix for simulator issue 😅

**Comment by jliukai** [comment]
i have this same error. works on a real device, but not on a simulator.

**Comment by nomanhassan96** [comment]
facing the same issue but on real device this time. Works the first three times, throws this exact error at the 4th recording attempt. 
Platform: IOS
Version: 3.6.0

**Comment by KrisLau** [comment]
@vygandas There's nothing to record on a simulator and I'm guessing Apple simulators dont handle it so it's not a problem with the package. Expo-AV recording is also the same 
> Audio from expo-av allows you to implement audio playback and recording in your app. ... Additionally, audio recording is not supported in the iOS Simulator.
Source: https://docs.expo.dev/versions/latest/sdk/audio

**Comment by rushant11** [comment]
when connected to headphones, the error has been gone.

**Comment by NewDimix** [comment]
Same issue here, is there any solution?
