### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by Shekhar-Satyanshu** [hyochan/react-native-audio-recorder-player#444]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Steps to reproduce the behavior

![Screenshot 2022-05-11 at 12 27 24 PM](https://user-images.githubusercontent.com/56349041/167788065-b73f51e8-0fb3-43f7-a0bc-f8738e716fbc.png)

**Comment by uxinnuendo** [comment]
@Shekhar-Satyanshu How did you solve it?

**Comment by paladinescamila** [comment]
@Shekhar-Satyanshu did you solve it?
