### ISSUE TITLE
Starting, stopping then starting a recording causes a fatal error

### ISSUE THREAD

**Issue by KrisLau** [hyochan/react-native-audio-recorder-player#445]
### Version of react-native-audio-recorder-player
3.5.0

### Version of React Native
0.64.2

### Platforms you faced the error (IOS or Android or both?)
Android (did not test on ios because the package only works on actual device)

### Expected behavior
the second time you start the recording, it should just override the original file

### Actual behavior
`Exception in native call of JS`

### Steps to reproduce the behavior

1. Start recording
2. Stop recording
3. Start recording

**Comment by KrisLau** [comment]
Not sure what happened but it just started working on its own

**Comment by fortunetalk** [comment]
how it works?
