### ISSUE TITLE
`currentPostion` callback variable flickering after several recordings

### ISSUE THREAD

**Issue by KrisLau** [hyochan/react-native-audio-recorder-player#446]
### Version of react-native-audio-recorder-player
3.5.0

### Version of React Native
0.64.2

### Platforms you faced the error (IOS or Android or both?)
Android (did not test on ios because the package only works on actual device)

### Expected behavior
`currentPostion` callback variable should go from 0 and count up the milliseconds one by one

### Actual behavior
`currentPostion` callback variable flickering after a number of recordings
![image](https://user-images.githubusercontent.com/46275463/168647932-7cdee80f-e481-4bf5-9fea-534ccacd88ef.png)

### Steps to reproduce the behavior
Not sure how many recordings before it started flickering but I'm guessing it will happen after about 30-50 recordings. My code for starting the recorder:
```
  const startRecorder = useCallback(async () => {
    const result = await audioRecorderPlayer.startRecorder();
    audioRecorderPlayer.addRecordBackListener(e => {
      setRecordSec(e.currentPosition);
    });
    setPath(result);
    setShowPlayer(false);
  }, []);
```

I am also getting random `Exception in the native call from JS errors` occasionally and after that error kills my app, the flickering stops temporarily

**Comment by hyochan** [comment]
@KrisLau I think this may happen if there is much interception in UI threads.

Could you try to `setSubscriptionDuration` to something slower like `0.5` and test again?

**Comment by KrisLau** [comment]
@hyochan that worked for me, thank you!
