### ISSUE TITLE
recording error on iOS physical device

### ISSUE THREAD

**Issue by ialirzgh** [hyochan/react-native-audio-recorder-player#459]
I am developing a chat application, with voice message features just like telegram
everything works as expected
but when I tried to test the application on a physical device
I get the error (error voice recorder instance on initialization)
It works perfectly in android, either simulator or physical device
but the problem occurs in ios physical device 
the devices I checked on and got the same issues are iPhone 13 Promax, and iPhone SE 2016

**Comment by wkchoong** [comment]
Everything just works perfect from Android real device even of using emulator but in iOS only works from simulator. When I try in iOS real device , the recording will not working. The duration always getting 0 second. Someone know this issue? My iOS software version is 15.4.1.

**Comment by ialirzgh** [comment]
I managed to fix it, the problem is, when you do setState or use useState during the start recording function it has interference with the procedure, so if you want to change a view by setting state, do it before recording, then use a setTimeout to make sure rerendering has been done, then call record method, and it works perfectly

**Comment by ialirzgh** [comment]
> Everything just works perfect from Android real device even of using emulator but in iOS only works from simulator. When I try in iOS real device , the recording will not working. The duration always getting 0 second. Someone know this issue? My iOS software version is 15.4.1.



I managed to fix it, the problem is, when you do setState or use useState during the start recording function it has interference with the procedure, so if you want to change a view by setting state, do it before recording, then use a setTimeout to make sure rerendering has been done, then call record method, and it works perfectly

**Comment by wkchoong** [comment]
const audioSet = {
      AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
      AudioSourceAndroid: AudioSourceAndroidType.MIC,
      OutputFormatAndroid: OutputFormatAndroidType.AAC_ADTS,
      AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high,
      AVNumberOfChannelsKeyIOS: 2,
      AVFormatIDKeyIOS: AVEncodingOption.aac,
      AVModeIOS: AVModeIOSOption.voicechat
    };
    const meteringEnabled = false;
    await audioRecorderPlayer.startRecorder(path, audioSet, meteringEnabled);
    
When I set audioSet to AVModeIOSOption.voicechat of AVModelOS and the recording function works fine from ios real device. But I getting low volume when recording the voice. If don't set AVModeIOS, the recording function not working again and will just record until like 1second or 0 second. I can only heard a while.

**Comment by hyochan** [comment]
@wkchoong Could you also try [the example project](https://github.com/hyochan/react-native-audio-recorder-player/tree/main/Example)?.

**Comment by wkchoong** [comment]
@hyochan Hi, I have fixed this issue for from last 2 months already.  That issue is because of I have installed the react-native-silent-listener for checking the user device is muted or not. So I have to remove the listener when I want to record the audio from iOS. Sorry for late reply here.

**Comment by hyochan** [comment]
Thanks for coming back. Will close the issue for now 👍

**Comment by omarhija10** [comment]
@wkchoong  we have the same issue  on the latest version could you please check it out 

thank you
