### ISSUE TITLE
AAC recorded on Android won't play on iOS

### ISSUE THREAD

**Issue by zawesh** [hyochan/react-native-audio-recorder-player#460]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Version of react-native-audio-recorder-player
3.5.1

### Version of React Native
0.68.0

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
AAC files recorded on Android play properly on iOS

### Actual behavior
AAC files recorded on Android do not play on iOS

### Steps to reproduce the behavior
Create audio file on Android
```js
const audioRP = new RNARPlayer()
audioRP.startRecorder(cachePath, {
    AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
    AudioSourceAndroid: AudioSourceAndroidType.MIC
})
const result = await audioRP.stopRecorder();
```
Test that it works on Android
```js
await audioRP.startPlayer(path);
```
Works fine. Also works fine on every media player on PC

Send it over to iOS, then try to play it
```js
const res = await audioRP.startPlayer(path);
```
Audio file does not play. There is no error and `addPlayBackListener` ticks once with 
```js
{
  currentPosition: 0
  duration: 0
  isMuted: false
}
```
Anybody else experiencing this?

**Comment by zawesh** [comment]
Missing this option:

```js
OutputFormatAndroid: OutputFormatAndroidType.AAC_ADTS,
```

**Comment by shawarmaz** [comment]
is it possible I'm getting a regression on this? 

Updated basically everything to latest

Android only spits out mp4 no matter the `AudioSet`
