### ISSUE TITLE
Doesn't work on iOS 15.5?

### ISSUE THREAD

**Issue by iovoz** [hyochan/react-native-audio-recorder-player#461]
### Version of react-native-audio-recorder-player
3.5.1

### Version of React Native
0.67.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
start record. 

### Actual behavior
record doesn't start

### Steps to reproduce the behabior
const audioSet = {
  OutputFormatAndroid: OutputFormatAndroidType.MPEG_4,
  AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
  AudioSourceAndroid: AudioSourceAndroidType.MIC,
  AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high,
  AVNumberOfChannelsKeyIOS: 2,
  AVFormatIDKeyIOS: AVEncodingOption.aac
};

 const path = Platform.select({
      ios: `${uuid.v4()}.m4a`,
      android: `${ReactNativeBlobUtil.fs.dirs.CacheDir}/${uuid.v4()}.mp4`
    });

    console.log(`path===================1`, path);
    const uri = await audioRecorderPlayer.startRecorder(path, audioSet);
    console.log(`uri===================2`);

the code execute stop at `const uri = await audioRecorderPlayer.startRecorder(path, audioSet);`, the next console log didn't execute..

**Comment by manjubhatt** [comment]
any update on this?
