### ISSUE TITLE
Help, I need the javascript version of this project! (Button.tsx and App.tsx => Button.js and App.js)

### ISSUE THREAD

**Issue by charbelmansour005** [hyochan/react-native-audio-recorder-player#464]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

3.5.1 = Version of react-native-audio-recorder-player 

0.69 Version of React Native

No Error

**Comment by AlkanV** [comment]
why? and most importantly you can use typescript in your javascript projects.

**Comment by hyochan** [comment]
Closes due to invalid. TS is a superset of js so you can do whatever you want by yourself.

Good luck 👍
