### ISSUE TITLE
stop recording when user stop talking

### ISSUE THREAD

**Issue by moloudayat** [hyochan/react-native-audio-recorder-player#473]
Hi there, I need to build a smart recorder that finishes recording when a user stops talking. Is there any attribute in your library that can help me do that? 
 thanks in advance
### Version of react-native-audio-recorder-player
^3.5.1
### Version of React Native
"0.63.4"
### Platforms you faced the error (IOS or Android or both?)
android and ios

**Comment by rvmoldova** [comment]
@moloudayat use `addRecordBackListener`. Based on `currentMetering` output you can stop recording

as an example: (just need to find that sweet THRESHOLD)
```ts
audioRecorderPlayer.addRecordBackListener(({ currentMetering }) => {
    if (currentMetering < THRESHOLD) {
        // stop recording
    }
})
```

Also `currentMetering` could have a lot of noise, just use some smoothing algorithms (e.g. [array-smooth](https://www.npmjs.com/package/array-smooth))

**Comment by hyochan** [comment]
Closing since it looks like it's already covered.

Thanks for your support 🙏 @rvmoldova
