### ISSUE TITLE
Sound recording problem due to changing storage access in Android 13

### ISSUE THREAD

**Issue by mohammad6vakili** [hyochan/react-native-audio-recorder-player#497]
### Version of react-native-audio-recorder-player
`3.5.1`

### Version of React Native
`0.70.6`

### Platforms you faced the error (IOS or Android or both?)
`Android`

### Expected behavior
Audio recording without forced access

### Actual behavior
Due to the change of storage access in Android 13, it is not possible to record audio

After many search about the permissions and reading the Android documents and reading the source of this library, I realized that this library does not actually work on Android 12 and 13.
According to this [document](https://developer.android.com/about/versions/13/behavior-changes-13), `WRITE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE` permissions do not exist in Android 13, and `READ_MEDIA_AUDIO` is available instead. Storage permissions are also always shown as `never_ask_again` . If `WRITE_EXTERNAL_STORAGE` is necessary in this library, and if this permission is not granted, the promise will be rejected.
Please check this because practically this library does not work on Android 12 and 13.

### check out this image @hyochan
![Source](https://user-images.githubusercontent.com/59134745/208630682-06609690-6e4a-4bdb-b6a7-ba72dc82867c.png)

**Comment by mohammad6vakili** [comment]
If someone who is familiar with Kotlin can help us in this matter and update this library.

**Comment by Malin88** [comment]
Same problem here :/

**Comment by pierroo** [comment]
did anyone here manage to fix this issue?
Would asking for the permission READ_MEDIA_AUDIO ourself make this library work on android 13?

Or is it doomed until the library itself asks for WRITE_EXTERNAL_STORAGE  under the hood that will always return false on android 13+?

**Comment by se1exin** [comment]
> If someone who is familiar with Kotlin can help us in this matter and update this library.

I've just raised a PR (#499) that fixes the issue, hopefully it gets merged soon 😄
