### ISSUE TITLE
[3.5.2] Android build fails with error: Unresolved reference: TIRAMISU

### ISSUE THREAD

**Issue by efstathiosntonas** [hyochan/react-native-audio-recorder-player#503]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Version of react-native-audio-recorder-player
`3.5.2`

### Version of React Native
`0.68.5`

### Platforms you faced the error (IOS or Android or both?)
Android, in my case Android 13 on a Samsung S22

### Expected behavior
expect to build

### Actual behavior
Throws error: 

`/Users/stathis/WebstormProjects/xxxx/node_modules/react-native-audio-recorder-player/android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt: (41, 65): Unresolved reference: TIRAMISU`

### Steps to reproduce the behabior
just install `3.5.2` and build on Android

edit: do we need to bump  `buildToolsVersion`,  `compileSdkVersion` and `targetSdkVersion` to `33.0.0`? 🤔 

`build.gradle` uses 31 though.

**Comment by hyochan** [comment]
I hope `3.5.3` works for you! Please come back if you have any further problems.
I just use the number `33` instead of `TRAMISU`. Looks like the variable is not detected in the lower build of Android.

@se1exin Hope you can either check this out!

**Comment by efstathiosntonas** [comment]
@hyochan thanks, I also thought to patch it with just the integer but I was waiting for your move since I’m not familiar with Kotlin. Will check it asap and let you know.
