### ISSUE TITLE
Generating wrong path file:////

### ISSUE THREAD

**Issue by nadeocfg** [hyochan/react-native-audio-recorder-player#509]
Hello, i have some weird bug. I'm try to record audio message, but promise return me wrong url, with four `/` instead of two:
`file:////data/user/0/com.example/cache/sound.aac`

```
const audioSet = {
  AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
  AudioSourceAndroid: AudioSourceAndroidType.MIC,
  AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high,
  AVNumberOfChannelsKeyIOS: 2,
  AVFormatIDKeyIOS: AVEncodingOption.aac,
  OutputFormatAndroid: OutputFormatAndroidType.AAC_ADTS,
};

const dirs = RNFetchBlob.fs.dirs;

const result = await record.instance?.startRecorder(
  `${dirs.CacheDir}/sound.aac`,
  audioSet,
  true,
);
console.log(result);
// file:////data/user/0/com.example/cache/sound.aac
```

When i dont pass uri argument `startRecorder()`, the result is `file:////data/user/0/com.example/cache/sound.mp4`.
When i pass full url to argument `startRecorder('file://data/user/0/com.example/cache/sound.aac')`, promise rejecting with
```
Possible Unhandled Promise Rejection (id: 0):
Error: file:/data/user/0/com.example/cache/sound.aac: open failed: ENOENT (No such file or directory)
```

### Version of react-native-audio-recorder-player
"react-native-audio-recorder-player": "^3.5.3"

### Version of React Native
"react-native": "0.70.6"

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Url with two `/`

### Actual behavior
Url with four `/`

**Comment by nadeocfg** [comment]
All permissions are granted, and i dont see any files on my device, after recording.

**Comment by nadeocfg** [comment]
Sorry, my fault. After restart emulator, `virtual microphone uses host audio input` set to false. When i return it to true, everything is work.

**Comment by prathameshkarambelkar** [comment]
@nadeocfg i am working on android device and not emulator, still getting the same file path url with 4  ' / ' , any ways to fix it?

**Comment by kbqdev** [comment]
@nadeocfg Bro how you solve this issues ? Please help.

**Comment by nadeocfg** [comment]
> @nadeocfg i am working on android device and not emulator, still getting the same file path url with 4 ' / ' , any ways to fix it?



> @nadeocfg Bro how you solve this issues ? Please help.

Sorry, guys, I don't know. I just relaunched my Android emulator, and somehow everything is working
