### ISSUE TITLE
How to save audio in mp3 format

### ISSUE THREAD

**Issue by Karan-Rampal** [hyochan/react-native-audio-recorder-player#522]
### Version of react-native-audio-recorder-player
3.5.3

### Version of React Native
0.70.5
### Expected behavior
Should save audio in mp3 format

### Actual behavior
saving audio in mp4 format

**Comment by hyochan** [comment]
I recommend you do this on the server-side using sw like [ffmpeg](https://ffmpeg.org). iOS and Android has license issue with mp3 codec if I remember correctly.
