### ISSUE TITLE
Not able to record more than twice on IOS | [Error: Error occured during recording]

### ISSUE THREAD

**Issue by iamyahyaahmed** [hyochan/react-native-audio-recorder-player#561]
I am using this in a chat application.
Setting the path as current time `const path = ${Date.now()}.m4a`
and I start recorder like this `const filePath = await audioRecorderPlayer.startRecorder(path);`
after 2 or 3 recordings I get an error `[Error: Error occured during recording]`
I am successfully able to record 2 or 3. maybe 4 times depending on length of audio

Recording stop 
` const result = await audioRecorderPlayer.stopRecorder();
      await audioRecorderPlayer.removeRecordBackListener();
`

### Expected behavior
I should be able to record as many as possible

### Actual behavior
recorder fails after 3 recordings

### Steps to reproduce the behabior
1. Start and stop recording 3 times

**Comment by iamyahyaahmed** [comment]
Help required 
any one else facing this?

**Comment by AlexanderVoronin-ux** [comment]
Have the same issue!

**Comment by bhavinatharva** [comment]
@hyochan 
Have the same issue!

**Comment by NewDimix** [comment]
Same issue here, is there any solution?

**Comment by hyochan** [comment]
Which version are you all using?
