### ISSUE TITLE
Installation Instructions Error

### ISSUE THREAD

**Issue by cliffgor** [hyochan/react-native-audio-recorder-player#567]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Version of react-native-audio-recorder-player
3.6.1

### Version of React Native
0.72.6
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
I was not able to build my application
### Actual behavior
When running the application I get an error 

Build file 'C:.\..\..\..\android\app\build.gradle' line: 109

![image](https://github.com/hyochan/react-native-audio-recorder-player/assets/17774205/e1f1d0ba-f111-488f-acee-80cc45be1078)

### Steps to reproduce the behabior
I followed the installation instructions from the documentation

**Comment by badkluster** [comment]
No hagas la instalacion manual, solo el paso siguiente a la instalación. RN la hace automáticamente
