### ISSUE TITLE
TypeError: Cannot read property 'startRecorder' of null

### ISSUE THREAD

**Issue by Rossella-Mascia-Neosyn** [hyochan/react-native-audio-recorder-player#576]
> Please fill the template to help you out. Also, please try the `Example` project compare before submiting the issue when you have certain issue with your project setup.

### Version of react-native-audio-recorder-player
"react-native-audio-recorder-player": "^3.6.4",

### Version of React Native
0.73
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Should start the registration
### Actual behavior
at the onLongPress event I have this error TypeError: Cannot read property 'startRecorder' of null
### Steps to reproduce the behabior
This is my repo: [https://github.com/neosyn-ee/react-native-neos-native-kit/tree/main ](https://github.com/neosyn-ee/react-native-neos-native-kit/tree/main) the component usage is inside the example folder instead the component is under the path src/components/AudioPlayerRecorder

1. go to inside example folder
2. yarn run start
3. yarn run android
4. click for a long time on the button with the microphone icon
5. it shows me the error TypeError: Cannot read property 'startRecorder' of null

**Comment by DonElect** [comment]
That repo no longer exist
