### ISSUE TITLE
Facing issue in iOS `CreateDataFile failed` and `Couldn't create a new audio file object`

### ISSUE THREAD

**Issue by darshil-evolution** [hyochan/react-native-audio-recorder-player#578]
Not able to recored the audio in iOS. Getting errors in xcode consloe   `CreateDataFile failed` and `Couldn't create a new audio file object`. In android working perfect. When I am giving just name in path like `audioFile.acc` it's working fine but when using RNFS path that time getting error.

 - "react-native-audio-recorder-player": "^3.6.5"
 - "react-native": "0.73.0"
 -  IOS
 
Expected behavior: I want to store audio on RNFS.DocumentDirectoryPath 
Actual behavior: Error starting recording: [Error: Error occured during initiating recorder]

```
  const currentDate = generateUniqueString().toString();
    const name = `${currentDate}.acc`;
const path = RNFS.DocumentDirectoryPath + `/${name}`;
await audioRecorderPlayer.startRecorder(path, audioSet, meteringEnabled);

```

**Comment by sooryranga** [comment]
I am having the same problem:

```
AudioFileObject.cpp:53     CreateDataFile failed
```

**Comment by sooryranga** [comment]
Figured it out, if you want specific file in IOS: you need to append `file://`

So the path would be:
```
const path = `file://${RNFS.DocumentDirectoryPath}/${name}`;
```

From code:
```
    func setAudioFileURL(path: String) {
        if (path == "DEFAULT") {
            let cachesDirectory = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
            audioFileURL = cachesDirectory.appendingPathComponent("sound.m4a")
        } else if (path.hasPrefix("http://") || path.hasPrefix("https://") || path.hasPrefix("file://")) {
            audioFileURL = URL(string: path)
        } else {
            let cachesDirectory = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
            audioFileURL = cachesDirectory.appendingPathComponent(path)
        }
    }
```

**Comment by sooryranga** [comment]
Will put out a diff to update Readme.

**Comment by sooryranga** [comment]
https://github.com/hyochan/react-native-audio-recorder-player/pull/589
