### ISSUE TITLE
Recording Interruption on iOS 3.6.2 -> 3.6.5

### ISSUE THREAD

**Issue by joshmohrer** [hyochan/react-native-audio-recorder-player#583]
in iOS, recording interruptions like phone calls or alarms have always been handled gracefully by pausing the recording.  I noticed recently that stopped, and recordings were totally lost if there was an interruption. There was mention of this behavior in a forum post or two from the 2020 era, but its always been fine for me.

I realized this problem emerged after installing 3.6.5 so I rolled back to 3.6.2 and its all fixed (I never used versions between those). Just wanted to flag this. If its helpful I can post more details.

**Comment by jogyfelix** [comment]
@joshmohrer Tried rolling back to 3.6.2 but its still resetting.how did you solved this? Can you share more details.

**Comment by pipi32167** [comment]
Look at [this](https://github.com/hyochan/react-native-audio-recorder-player/pull/600)
